(define (problem problem-test)
	(:domain domain-test)
(:objects ['d1', 'd2'] - disease
		d1 d2 t1 t2 t3 a1 a2 a3 a7 a4 b1 b2 c1 c2 p1 p2 g1 g2 - node
)(:init
	(initialNode d1 t1)
	(initialNode d2 a4)
	(goalNode d1 g1)
	(goalNode d2 g2)
	(predecessorNode t1 a1)
	(predecessorNode t1 a2)
	(predecessorNode t2 g1)
	(predecessorNode t2 a3)
	(predecessorNode t3 a7)
	(predecessorNode t3 g2)
	(predecessorNode a1 p1)
	(predecessorNode a2 p1)
	(predecessorNode a3 g1)
	(predecessorNode a7 g2)
	(predecessorNode a4 t3)
	(predecessorNode b1 b2)
	(predecessorNode b2 p2)
	(predecessorNode c1 c2)
	(predecessorNode c2 p2)
	(predecessorNode p1 b1)
	(predecessorNode p1 c1)
	(predecessorNode p2 t2)
	
)
)