(define (problem mitplan-problem)
	(:domain mitplan-domain)
(:objects MDD AD - disease
	LOWMOOD LOWENERGY SUICIDE SYMPTOMSIMPROVE ECT ISPHYSICAL ISSOCIAL SYMPTOMSIMPROVE2 THERAPY CHECKUP SSRI DOECT STABILIZERS CHOLINESTERASE COGNITIVESUPPORT PHYSICAL NUTRITION THERAPY2 SOCIAL TRIALS G_MDD G_AD DOPAMINE HOSPITAL - node
	ro1 ro2 - revId
	DATA_LOWMOOD DATA_LOWENERGY DATA_SUICIDE DATA_SYMPTOMSIMPROVE DATA_ECT DATA_ISPHYSICAL DATA_ISSOCIAL DATA_SYMPTOMSIMPROVE2 - DataItem
)
(:init
	(= (decisionBranchMin MDD LOWMOOD LOWENERGY) 1)
	(= (decisionBranchMax MDD LOWMOOD LOWENERGY) 1)
	(= (decisionBranchMin MDD LOWMOOD THERAPY) 0)
	(= (decisionBranchMax MDD LOWMOOD THERAPY) 0)
	(= (decisionBranchMin MDD LOWENERGY THERAPY) 0)
	(= (decisionBranchMax MDD LOWENERGY THERAPY) 0)
	(= (decisionBranchMin MDD LOWENERGY SUICIDE) 1)
	(= (decisionBranchMax MDD LOWENERGY SUICIDE) 1)
	(= (decisionBranchMin MDD SUICIDE THERAPY) 0)
	(= (decisionBranchMax MDD SUICIDE THERAPY) 0)
	(= (decisionBranchMin MDD SUICIDE SSRI) 1)
	(= (decisionBranchMax MDD SUICIDE SSRI) 1)
	(= (decisionBranchMin MDD SYMPTOMSIMPROVE G_MDD) 1)
	(= (decisionBranchMax MDD SYMPTOMSIMPROVE G_MDD) 1)
	(= (decisionBranchMin MDD SYMPTOMSIMPROVE ECT) 0)
	(= (decisionBranchMax MDD SYMPTOMSIMPROVE ECT) 0)
	(= (decisionBranchMin MDD ECT DOECT) 1)
	(= (decisionBranchMax MDD ECT DOECT) 1)
	(= (decisionBranchMin MDD ECT STABILIZERS) 0)
	(= (decisionBranchMax MDD ECT STABILIZERS) 0)
	(= (decisionBranchMin MDD ECT HOSPITAL) 1)
	(= (decisionBranchMax MDD ECT HOSPITAL) 1)
	(= (decisionBranchMin AD ISPHYSICAL PHYSICAL) 1)
	(= (decisionBranchMax AD ISPHYSICAL PHYSICAL) 1)
	(= (decisionBranchMin AD ISPHYSICAL NUTRITION) 0)
	(= (decisionBranchMax AD ISPHYSICAL NUTRITION) 0)
	(= (decisionBranchMin AD ISSOCIAL SOCIAL) 0)
	(= (decisionBranchMax AD ISSOCIAL SOCIAL) 0)
	(= (decisionBranchMin AD ISSOCIAL NUTRITION) 1)
	(= (decisionBranchMax AD ISSOCIAL NUTRITION) 1)
	(= (decisionBranchMin AD SYMPTOMSIMPROVE2 G_AD) 1)
	(= (decisionBranchMax AD SYMPTOMSIMPROVE2 G_AD) 1)
	(= (decisionBranchMin AD SYMPTOMSIMPROVE2 TRIALS) 0)
	(= (decisionBranchMax AD SYMPTOMSIMPROVE2 TRIALS) 0)

	(dataItem LOWMOOD DATA_LOWMOOD)
	(dataItem LOWENERGY DATA_LOWENERGY)
	(dataItem SUICIDE DATA_SUICIDE)
	(dataItem SYMPTOMSIMPROVE DATA_SYMPTOMSIMPROVE)
	(dataItem ECT DATA_ECT)
	(dataItem ISPHYSICAL DATA_ISPHYSICAL)
	(dataItem ISSOCIAL DATA_ISSOCIAL)
	(dataItem SYMPTOMSIMPROVE2 DATA_SYMPTOMSIMPROVE2)

	(= (dataValue DATA_LOWMOOD) 1)
	(= (dataValue DATA_LOWENERGY) 1)
	(= (dataValue DATA_SUICIDE) 1)
	(= (dataValue DATA_SYMPTOMSIMPROVE) 1)
	(= (dataValue DATA_ISPHYSICAL) 1)
	(= (dataValue DATA_ISSOCIAL) 1)
	(= (dataValue DATA_SYMPTOMSIMPROVE2) 0)
	(= (dataValue DATA_ECT) 0)

	(initialNode MDD LOWMOOD)
	(initialNode AD CHOLINESTERASE)
	(goalNode MDD G_MDD)
	(goalNode AD G_AD)

	(predecessorNode LOWMOOD LOWENERGY)
	(predecessorNode LOWMOOD THERAPY)
	(predecessorNode LOWENERGY THERAPY)
	(predecessorNode LOWENERGY SUICIDE)
	(predecessorNode THERAPY CHECKUP)
	(predecessorNode SUICIDE THERAPY)
	(predecessorNode SUICIDE SSRI)
	(predecessorNode CHECKUP SYMPTOMSIMPROVE)
	(predecessorNode SSRI THERAPY)
	(predecessorNode SSRI DOPAMINE)
	(predecessorNode SYMPTOMSIMPROVE G_MDD)
	(predecessorNode SYMPTOMSIMPROVE ECT)
	(predecessorNode ECT DOECT)
	(predecessorNode ECT STABILIZERS)
	(predecessorNode ECT HOSPITAL)
	(predecessorNode DOECT STABILIZERS)
	(predecessorNode STABILIZERS G_MDD)
	(predecessorNode CHOLINESTERASE COGNITIVESUPPORT)
	(predecessorNode COGNITIVESUPPORT ISPHYSICAL)
	(predecessorNode ISPHYSICAL PHYSICAL)
	(predecessorNode ISPHYSICAL NUTRITION)
	(predecessorNode PHYSICAL ISSOCIAL)
	(predecessorNode NUTRITION THERAPY2)
	(predecessorNode ISSOCIAL SOCIAL)
	(predecessorNode ISSOCIAL NUTRITION)
	(predecessorNode THERAPY2 SYMPTOMSIMPROVE2)
	(predecessorNode SOCIAL NUTRITION)
	(predecessorNode SYMPTOMSIMPROVE2 G_AD)
	(predecessorNode SYMPTOMSIMPROVE2 TRIALS)
	(predecessorNode TRIALS G_AD)
	(predecessorNode DOPAMINE THERAPY)
	(predecessorNode HOSPITAL STABILIZERS)

	(actionNode THERAPY)
	(actionNode CHECKUP)
	(actionNode SSRI)
	(actionNode DOECT)
	(actionNode STABILIZERS)
	(actionNode CHOLINESTERASE)
	(actionNode COGNITIVESUPPORT)
	(actionNode PHYSICAL)
	(actionNode NUTRITION)
	(actionNode THERAPY2)
	(actionNode SOCIAL)
	(actionNode TRIALS)
	(decisionNode LOWMOOD)
	(decisionNode LOWENERGY)
	(decisionNode SUICIDE)
	(decisionNode SYMPTOMSIMPROVE)
	(decisionNode ECT)
	(decisionNode ISPHYSICAL)
	(decisionNode ISSOCIAL)
	(decisionNode SYMPTOMSIMPROVE2)
	(actionNode DOPAMINE)
	(actionNode HOSPITAL)

	(originalAction THERAPY)
	(originalAction CHECKUP)
	(originalAction SSRI)
	(originalAction DOECT)
	(originalAction STABILIZERS)
	(originalAction CHOLINESTERASE)
	(originalAction COGNITIVESUPPORT)
	(originalAction PHYSICAL)
	(originalAction NUTRITION)
	(originalAction THERAPY2)
	(originalAction SOCIAL)
	(originalAction TRIALS)

	(revisionAction DOPAMINE ro1)
	(revisionAction HOSPITAL ro2)

	(= (revisionFlag LOWMOOD ro1) 0)
	(= (revisionFlag LOWENERGY ro1) 0)
	(= (revisionFlag THERAPY ro1) 0)
	(= (revisionFlag SUICIDE ro1) 0)
	(= (revisionFlag CHECKUP ro1) 0)
	(= (revisionFlag SSRI ro1) 0)
	(= (revisionFlag SYMPTOMSIMPROVE ro1) 0)
	(= (revisionFlag G_MDD ro1) 0)
	(= (revisionFlag ECT ro1) 0)
	(= (revisionFlag DOECT ro1) 0)
	(= (revisionFlag STABILIZERS ro1) 0)
	(= (revisionFlag CHOLINESTERASE ro1) 0)
	(= (revisionFlag COGNITIVESUPPORT ro1) 0)
	(= (revisionFlag ISPHYSICAL ro1) 0)
	(= (revisionFlag PHYSICAL ro1) 0)
	(= (revisionFlag NUTRITION ro1) 0)
	(= (revisionFlag ISSOCIAL ro1) 0)
	(= (revisionFlag THERAPY2 ro1) 0)
	(= (revisionFlag SOCIAL ro1) 0)
	(= (revisionFlag SYMPTOMSIMPROVE2 ro1) 0)
	(= (revisionFlag G_AD ro1) 0)
	(= (revisionFlag TRIALS ro1) 1)
	(= (revisionFlag DOPAMINE ro1) 0)
	(= (revisionFlag HOSPITAL ro1) 0)

	(= (revisionSequenceNumNodes ro1) 1)
	(= (numNodesToReplace ro1) 1)
	(= (revisionCount ro1) 0)
	(= (revisionIDPass MDD ro1) 0)
	(= (revisionIDPass AD ro1) 0)

	(= (revisionFlag LOWMOOD ro2) 0)
	(= (revisionFlag LOWENERGY ro2) 0)
	(= (revisionFlag THERAPY ro2) 0)
	(= (revisionFlag SUICIDE ro2) 0)
	(= (revisionFlag CHECKUP ro2) 0)
	(= (revisionFlag SSRI ro2) 0)
	(= (revisionFlag SYMPTOMSIMPROVE ro2) 0)
	(= (revisionFlag G_MDD ro2) 0)
	(= (revisionFlag ECT ro2) 1)
	(= (revisionFlag DOECT ro2) 0)
	(= (revisionFlag STABILIZERS ro2) 0)
	(= (revisionFlag CHOLINESTERASE ro2) 0)
	(= (revisionFlag COGNITIVESUPPORT ro2) 0)
	(= (revisionFlag ISPHYSICAL ro2) 0)
	(= (revisionFlag PHYSICAL ro2) 0)
	(= (revisionFlag NUTRITION ro2) 0)
	(= (revisionFlag ISSOCIAL ro2) 0)
	(= (revisionFlag THERAPY2 ro2) 0)
	(= (revisionFlag SOCIAL ro2) 0)
	(= (revisionFlag SYMPTOMSIMPROVE2 ro2) 0)
	(= (revisionFlag G_AD ro2) 0)
	(= (revisionFlag TRIALS ro2) 1)
	(= (revisionFlag DOPAMINE ro2) 0)
	(= (revisionFlag HOSPITAL ro2) 0)

	(= (revisionSequenceNumNodes ro2) 2)
	(= (numNodesToReplace ro2) 1)
	(= (revisionCount ro2) 0)
	(= (revisionIDPass MDD ro2) 0)
	(= (revisionIDPass AD ro2) 0)


	(= (allRevisionsPass MDD) 0)
	(= (allRevisionsPass AD) 0)
	(= (numRevisionIDs MDD) 1)
	(= (numRevisionIDs AD) 1)

	(anyRevisionOps MDD)
	(anyRevisionOps AD)

	(= (tentativeGoalCount) 0)

	(= (numGoals) 2)

	(= (total-execcost) 0)
	(= (total-cost) 0)
	(= (total-burden) 0)
	(= (total-nonadherence) 0)
	(= (total-duration) 0)

	(= (nodeExecCost LOWMOOD) 0)
	(= (nodeCost LOWMOOD) 0)
	(= (nodeBurden LOWMOOD) 0)
	(= (nodeNonadherence LOWMOOD) 0)
	(= (nodeStartTime LOWMOOD) 0)
	(= (nodeEndTime LOWMOOD) 0)
	(= (nodeDuration LOWMOOD) 0)

	(= (nodeExecCost LOWENERGY) 0)
	(= (nodeCost LOWENERGY) 0)
	(= (nodeBurden LOWENERGY) 0)
	(= (nodeNonadherence LOWENERGY) 0)
	(= (nodeStartTime LOWENERGY) 0)
	(= (nodeEndTime LOWENERGY) 0)
	(= (nodeDuration LOWENERGY) 0)

	(= (nodeExecCost THERAPY) 0)
	(= (nodeCost THERAPY) 0)
	(= (nodeBurden THERAPY) 0)
	(= (nodeNonadherence THERAPY) 0)
	(= (nodeStartTime THERAPY) 0)
	(= (nodeEndTime THERAPY) 0)
	(= (nodeDuration THERAPY) 0)

	(= (nodeExecCost SUICIDE) 0)
	(= (nodeCost SUICIDE) 0)
	(= (nodeBurden SUICIDE) 0)
	(= (nodeNonadherence SUICIDE) 0)
	(= (nodeStartTime SUICIDE) 0)
	(= (nodeEndTime SUICIDE) 0)
	(= (nodeDuration SUICIDE) 0)

	(= (nodeExecCost CHECKUP) 0)
	(= (nodeCost CHECKUP) 0)
	(= (nodeBurden CHECKUP) 0)
	(= (nodeNonadherence CHECKUP) 0)
	(= (nodeStartTime CHECKUP) 0)
	(= (nodeEndTime CHECKUP) 0)
	(= (nodeDuration CHECKUP) 0)

	(= (nodeExecCost SSRI) 0)
	(= (nodeCost SSRI) 0)
	(= (nodeBurden SSRI) 0)
	(= (nodeNonadherence SSRI) 0)
	(= (nodeStartTime SSRI) 0)
	(= (nodeEndTime SSRI) 0)
	(= (nodeDuration SSRI) 0)

	(= (nodeExecCost SYMPTOMSIMPROVE) 0)
	(= (nodeCost SYMPTOMSIMPROVE) 0)
	(= (nodeBurden SYMPTOMSIMPROVE) 0)
	(= (nodeNonadherence SYMPTOMSIMPROVE) 0)
	(= (nodeStartTime SYMPTOMSIMPROVE) 0)
	(= (nodeEndTime SYMPTOMSIMPROVE) 0)
	(= (nodeDuration SYMPTOMSIMPROVE) 0)

	(= (nodeExecCost G_MDD) 0)
	(= (nodeCost G_MDD) 0)
	(= (nodeBurden G_MDD) 0)
	(= (nodeNonadherence G_MDD) 0)
	(= (nodeStartTime G_MDD) 0)
	(= (nodeEndTime G_MDD) 0)
	(= (nodeDuration G_MDD) 0)

	(= (nodeExecCost ECT) 0)
	(= (nodeCost ECT) 0)
	(= (nodeBurden ECT) 0)
	(= (nodeNonadherence ECT) 0)
	(= (nodeStartTime ECT) 0)
	(= (nodeEndTime ECT) 0)
	(= (nodeDuration ECT) 0)

	(= (nodeExecCost DOECT) 0)
	(= (nodeCost DOECT) 0)
	(= (nodeBurden DOECT) 0)
	(= (nodeNonadherence DOECT) 0)
	(= (nodeStartTime DOECT) 0)
	(= (nodeEndTime DOECT) 0)
	(= (nodeDuration DOECT) 0)

	(= (nodeExecCost STABILIZERS) 0)
	(= (nodeCost STABILIZERS) 0)
	(= (nodeBurden STABILIZERS) 0)
	(= (nodeNonadherence STABILIZERS) 0)
	(= (nodeStartTime STABILIZERS) 0)
	(= (nodeEndTime STABILIZERS) 0)
	(= (nodeDuration STABILIZERS) 0)

	(= (nodeExecCost CHOLINESTERASE) 0)
	(= (nodeCost CHOLINESTERASE) 0)
	(= (nodeBurden CHOLINESTERASE) 0)
	(= (nodeNonadherence CHOLINESTERASE) 0)
	(= (nodeStartTime CHOLINESTERASE) 0)
	(= (nodeEndTime CHOLINESTERASE) 0)
	(= (nodeDuration CHOLINESTERASE) 0)

	(= (nodeExecCost COGNITIVESUPPORT) 0)
	(= (nodeCost COGNITIVESUPPORT) 0)
	(= (nodeBurden COGNITIVESUPPORT) 0)
	(= (nodeNonadherence COGNITIVESUPPORT) 0)
	(= (nodeStartTime COGNITIVESUPPORT) 0)
	(= (nodeEndTime COGNITIVESUPPORT) 0)
	(= (nodeDuration COGNITIVESUPPORT) 0)

	(= (nodeExecCost ISPHYSICAL) 0)
	(= (nodeCost ISPHYSICAL) 0)
	(= (nodeBurden ISPHYSICAL) 0)
	(= (nodeNonadherence ISPHYSICAL) 0)
	(= (nodeStartTime ISPHYSICAL) 0)
	(= (nodeEndTime ISPHYSICAL) 0)
	(= (nodeDuration ISPHYSICAL) 0)

	(= (nodeExecCost PHYSICAL) 0)
	(= (nodeCost PHYSICAL) 0)
	(= (nodeBurden PHYSICAL) 0)
	(= (nodeNonadherence PHYSICAL) 0)
	(= (nodeStartTime PHYSICAL) 0)
	(= (nodeEndTime PHYSICAL) 0)
	(= (nodeDuration PHYSICAL) 0)

	(= (nodeExecCost NUTRITION) 0)
	(= (nodeCost NUTRITION) 0)
	(= (nodeBurden NUTRITION) 0)
	(= (nodeNonadherence NUTRITION) 0)
	(= (nodeStartTime NUTRITION) 0)
	(= (nodeEndTime NUTRITION) 0)
	(= (nodeDuration NUTRITION) 0)

	(= (nodeExecCost ISSOCIAL) 0)
	(= (nodeCost ISSOCIAL) 0)
	(= (nodeBurden ISSOCIAL) 0)
	(= (nodeNonadherence ISSOCIAL) 0)
	(= (nodeStartTime ISSOCIAL) 0)
	(= (nodeEndTime ISSOCIAL) 0)
	(= (nodeDuration ISSOCIAL) 0)

	(= (nodeExecCost THERAPY2) 0)
	(= (nodeCost THERAPY2) 0)
	(= (nodeBurden THERAPY2) 0)
	(= (nodeNonadherence THERAPY2) 0)
	(= (nodeStartTime THERAPY2) 0)
	(= (nodeEndTime THERAPY2) 0)
	(= (nodeDuration THERAPY2) 0)

	(= (nodeExecCost SOCIAL) 0)
	(= (nodeCost SOCIAL) 0)
	(= (nodeBurden SOCIAL) 0)
	(= (nodeNonadherence SOCIAL) 0)
	(= (nodeStartTime SOCIAL) 0)
	(= (nodeEndTime SOCIAL) 0)
	(= (nodeDuration SOCIAL) 0)

	(= (nodeExecCost SYMPTOMSIMPROVE2) 0)
	(= (nodeCost SYMPTOMSIMPROVE2) 0)
	(= (nodeBurden SYMPTOMSIMPROVE2) 0)
	(= (nodeNonadherence SYMPTOMSIMPROVE2) 0)
	(= (nodeStartTime SYMPTOMSIMPROVE2) 0)
	(= (nodeEndTime SYMPTOMSIMPROVE2) 0)
	(= (nodeDuration SYMPTOMSIMPROVE2) 0)

	(= (nodeExecCost G_AD) 0)
	(= (nodeCost G_AD) 0)
	(= (nodeBurden G_AD) 0)
	(= (nodeNonadherence G_AD) 0)
	(= (nodeStartTime G_AD) 0)
	(= (nodeEndTime G_AD) 0)
	(= (nodeDuration G_AD) 0)

	(= (nodeExecCost TRIALS) 0)
	(= (nodeCost TRIALS) 0)
	(= (nodeBurden TRIALS) 0)
	(= (nodeNonadherence TRIALS) 0)
	(= (nodeStartTime TRIALS) 0)
	(= (nodeEndTime TRIALS) 0)
	(= (nodeDuration TRIALS) 0)

	(= (nodeExecCost DOPAMINE) 0)
	(= (nodeCost DOPAMINE) 0)
	(= (nodeBurden DOPAMINE) 0)
	(= (nodeNonadherence DOPAMINE) 0)
	(= (nodeStartTime DOPAMINE) 0)
	(= (nodeEndTime DOPAMINE) 0)
	(= (nodeDuration DOPAMINE) 0)

	(= (nodeExecCost HOSPITAL) 0)
	(= (nodeCost HOSPITAL) 0)
	(= (nodeBurden HOSPITAL) 0)
	(= (nodeNonadherence HOSPITAL) 0)
	(= (nodeStartTime HOSPITAL) 0)
	(= (nodeEndTime HOSPITAL) 0)
	(= (nodeDuration HOSPITAL) 0)

)

(:goal (and	(treatmentPlanReady MDD G_MDD)
	(treatmentPlanReady AD G_AD)
	)
)

(:metric minimize
	(+ (total-execcost)
(total-cost)
(total-burden)
(total-nonadherence)
(total-duration)
))
)