(define (problem all-problem)
	(:domain  mitplan-domain)
(:objects afib_c ckd_c htn_c - disease
			afib_g afib_a_cardioversion afib_a_anticoagulation afib_a_rate_control_1 afib_a_rate_control_maintenance_1 afib_a_rate_control_maintenance_2 afib_a_rhytm_control_maintenance_1 afib_a_rhytm_control_maintenance_2 afib_a_pill_in_a_pocket afib_d_special_circumstances afib_d_afib_type afib_d_symptom_recurrence afib_d_symptoms_improve afib_d_symptoms_resolve afib_d_afib_recurs afib_d_tachychardia afib_p1 afib_p2 afib_p3 afib_p4 afib_d1 afib_d2 afib_d3 afib_d4 ckd_g ckd_a_phosphate_binders ckd_a_esa ckd_a_iron_therapy ckd_a_ace_inhibitor ckd_a_aspirin ckd_a_lifestyle_management ckd_d_egfr ckd_d_hemoglobin_level ckd_d_metabolic_abnormality ckd_d_ferritin_level ckd_p1 ckd_p2 ckd_p3 ckd_p4 ckd_p5 ckd_p6 ckd_d1 ckd_d2 ckd_d3 ckd_d4 htn_g htn_a_lifestyle_management htn_a_step1_acei htn_a_step1_ccb htn_a_step2_acei htn_a_step2_diuretics htn_a_step3_acei htn_a_step3_ccb htn_a_step3_diuretric htn_a_specialist_consult htn_d_age_under_55 htn_d_bp_controlled_1 htn_d_bp_controlled_2 htn_d_bp_controlled_3 htn_p1 htn_p2 htn_p3 htn_p4 htn_p5 htn_p6 htn_d1 htn_d2 htn_d3 rev-dummy-1 alt-40a95234 rev-dummy-2 alt-39999914 rev-afib-scb-1 alt-37536fba rev-afib-scb-2 alt-c9ca60ae rev-ckd-warfarin alt-ed39ae97 rev-ckd-doac alt-b0ef3768 - node
			remove-bb-1 remove-bb-2 replace-cpb-with-scb-1 replace-cpb-with-scb-2 replace-low-dose-aspirin-with-warfarin replace-low-dose-aspirin-with-doac - revId
			afib_special_circumstances afib_afib_type afib_symptom_recurrence afib_symptoms_improve afib_symptoms_resolve afib_afib_recurs afib_tachychardia ckd_egfr ckd_hemoglobin_level ckd_metabolic_abnormality ckd_ferritin_level htn_age_under_55 htn_bp_controlled_1 htn_bp_controlled_2 htn_bp_controlled_3 - DataItem
)

(:init 	(= (decisionBranchMin afib_c afib_d_special_circumstances afib_a_rate_control_1) "0)
	(= (decisionBranchMax afib_c afib_d_special_circumstances afib_a_rate_control_1) 0")
	(= (decisionBranchMin afib_c afib_d_special_circumstances afib_d_afib_type) "1)
	(= (decisionBranchMax afib_c afib_d_special_circumstances afib_d_afib_type) 1")
	(= (decisionBranchMin afib_c afib_d_afib_type afib_d_symptom_recurrence) "1)
	(= (decisionBranchMax afib_c afib_d_afib_type afib_d_symptom_recurrence) 1")
	(= (decisionBranchMin afib_c afib_d_afib_type afib_a_cardioversion) "2)
	(= (decisionBranchMax afib_c afib_d_afib_type afib_a_cardioversion) 2")
	(= (decisionBranchMin afib_c afib_d_symptom_recurrence afib_a_pill_in_a_pocket) "0)
	(= (decisionBranchMax afib_c afib_d_symptom_recurrence afib_a_pill_in_a_pocket) 0")
	(= (decisionBranchMin afib_c afib_d_symptom_recurrence afib_a_rhytm_control_maintenance_1) "1)
	(= (decisionBranchMax afib_c afib_d_symptom_recurrence afib_a_rhytm_control_maintenance_1) 1")
	(= (decisionBranchMin afib_c afib_d_symptom_recurrence rev-afib-scb-1) "1)
	(= (decisionBranchMax afib_c afib_d_symptom_recurrence rev-afib-scb-1) 1")
	(= (decisionBranchMin afib_c afib_d_symptoms_improve afib_a_rate_control_maintenance_1) "0)
	(= (decisionBranchMax afib_c afib_d_symptoms_improve afib_a_rate_control_maintenance_1) 0")
	(= (decisionBranchMin afib_c afib_d_symptoms_improve afib_p2) "1)
	(= (decisionBranchMax afib_c afib_d_symptoms_improve afib_p2) 1")
	(= (decisionBranchMin afib_c afib_d_symptoms_improve rev-dummy-1) "0)
	(= (decisionBranchMax afib_c afib_d_symptoms_improve rev-dummy-1) 0")
	(= (decisionBranchMin afib_c afib_d_symptoms_resolve afib_d_afib_type) "0)
	(= (decisionBranchMax afib_c afib_d_symptoms_resolve afib_d_afib_type) 0")
	(= (decisionBranchMin afib_c afib_d_symptoms_resolve afib_a_rate_control_maintenance_1) "1)
	(= (decisionBranchMax afib_c afib_d_symptoms_resolve afib_a_rate_control_maintenance_1) 1")
	(= (decisionBranchMin afib_c afib_d_symptoms_resolve rev-dummy-1) "1)
	(= (decisionBranchMax afib_c afib_d_symptoms_resolve rev-dummy-1) 1")
	(= (decisionBranchMin afib_c afib_d_afib_recurs afib_a_rhytm_control_maintenance_2) "1)
	(= (decisionBranchMax afib_c afib_d_afib_recurs afib_a_rhytm_control_maintenance_2) 1")
	(= (decisionBranchMin afib_c afib_d_afib_recurs afib_d2) "0)
	(= (decisionBranchMax afib_c afib_d_afib_recurs afib_d2) 0")
	(= (decisionBranchMin afib_c afib_d_afib_recurs rev-afib-scb-2) "1)
	(= (decisionBranchMax afib_c afib_d_afib_recurs rev-afib-scb-2) 1")
	(= (decisionBranchMin afib_c afib_d_tachychardia afib_a_rate_control_maintenance_2) "1)
	(= (decisionBranchMax afib_c afib_d_tachychardia afib_a_rate_control_maintenance_2) 1")
	(= (decisionBranchMin afib_c afib_d_tachychardia afib_d1) "0)
	(= (decisionBranchMax afib_c afib_d_tachychardia afib_d1) 0")
	(= (decisionBranchMin afib_c afib_d_tachychardia rev-dummy-2) "1)
	(= (decisionBranchMax afib_c afib_d_tachychardia rev-dummy-2) 1")
	(= (decisionBranchMin ckd_c ckd_d_egfr ckd_d4) "2)
	(= (decisionBranchMax ckd_c ckd_d_egfr ckd_d4) 2")
	(= (decisionBranchMin ckd_c ckd_d_egfr ckd_p3) "1)
	(= (decisionBranchMax ckd_c ckd_d_egfr ckd_p3) 1")
	(= (decisionBranchMin ckd_c ckd_d_hemoglobin_level ckd_a_esa) "1)
	(= (decisionBranchMax ckd_c ckd_d_hemoglobin_level ckd_a_esa) 1")
	(= (decisionBranchMin ckd_c ckd_d_hemoglobin_level ckd_d1) "2)
	(= (decisionBranchMax ckd_c ckd_d_hemoglobin_level ckd_d1) 2")
	(= (decisionBranchMin ckd_c ckd_d_metabolic_abnormality ckd_a_phosphate_binders) "1)
	(= (decisionBranchMax ckd_c ckd_d_metabolic_abnormality ckd_a_phosphate_binders) 1")
	(= (decisionBranchMin ckd_c ckd_d_metabolic_abnormality ckd_d3) "0)
	(= (decisionBranchMax ckd_c ckd_d_metabolic_abnormality ckd_d3) 0")
	(= (decisionBranchMin ckd_c ckd_d_ferritin_level ckd_a_iron_therapy) "1)
	(= (decisionBranchMax ckd_c ckd_d_ferritin_level ckd_a_iron_therapy) 1")
	(= (decisionBranchMin ckd_c ckd_d_ferritin_level ckd_d2) "2)
	(= (decisionBranchMax ckd_c ckd_d_ferritin_level ckd_d2) 2")
	(= (decisionBranchMin htn_c htn_d_age_under_55 htn_a_step1_acei) "1)
	(= (decisionBranchMax htn_c htn_d_age_under_55 htn_a_step1_acei) 1")
	(= (decisionBranchMin htn_c htn_d_age_under_55 htn_a_step1_ccb) "0)
	(= (decisionBranchMax htn_c htn_d_age_under_55 htn_a_step1_ccb) 0")
	(= (decisionBranchMin htn_c htn_d_bp_controlled_1 htn_d3) "1)
	(= (decisionBranchMax htn_c htn_d_bp_controlled_1 htn_d3) 1")
	(= (decisionBranchMin htn_c htn_d_bp_controlled_1 htn_p2) "0)
	(= (decisionBranchMax htn_c htn_d_bp_controlled_1 htn_p2) 0")
	(= (decisionBranchMin htn_c htn_d_bp_controlled_2 htn_d2) "1)
	(= (decisionBranchMax htn_c htn_d_bp_controlled_2 htn_d2) 1")
	(= (decisionBranchMin htn_c htn_d_bp_controlled_2 htn_p4) "0)
	(= (decisionBranchMax htn_c htn_d_bp_controlled_2 htn_p4) 0")
	(= (decisionBranchMin htn_c htn_d_bp_controlled_3 htn_d1) "1)
	(= (decisionBranchMax htn_c htn_d_bp_controlled_3 htn_d1) 1")
	(= (decisionBranchMin htn_c htn_d_bp_controlled_3 htn_a_specialist_consult) "0)
	(= (decisionBranchMax htn_c htn_d_bp_controlled_3 htn_a_specialist_consult) 0")

	(dataItem afib_d_special_circumstances afib_special_circumstances)
	(dataItem afib_d_afib_type afib_afib_type)
	(dataItem afib_d_symptom_recurrence afib_symptom_recurrence)
	(dataItem afib_d_symptoms_improve afib_symptoms_improve)
	(dataItem afib_d_symptoms_resolve afib_symptoms_resolve)
	(dataItem afib_d_afib_recurs afib_afib_recurs)
	(dataItem afib_d_tachychardia afib_tachychardia)
	(dataItem ckd_d_egfr ckd_egfr)
	(dataItem ckd_d_hemoglobin_level ckd_hemoglobin_level)
	(dataItem ckd_d_metabolic_abnormality ckd_metabolic_abnormality)
	(dataItem ckd_d_ferritin_level ckd_ferritin_level)
	(dataItem htn_d_age_under_55 htn_age_under_55)
	(dataItem htn_d_bp_controlled_1 htn_bp_controlled_1)
	(dataItem htn_d_bp_controlled_2 htn_bp_controlled_2)
	(dataItem htn_d_bp_controlled_3 htn_bp_controlled_3)

	(= (dataValue afib_special_circumstances) 1)
	(= (dataValue afib_afib_type) 2)
	(= (dataValue afib_symptom_recurrence) 0)
	(= (dataValue afib_symptoms_improve) 1)
	(= (dataValue afib_symptoms_resolve) 1)
	(= (dataValue afib_afib_recurs) 1)
	(= (dataValue afib_tachychardia) 1)
	(= (dataValue ckd_egfr) 1)
	(= (dataValue ckd_hemoglobin_level) 1)
	(= (dataValue ckd_metabolic_abnormality) 1)
	(= (dataValue ckd_ferritin_level) 1)
	(= (dataValue htn_age_under_55) 0)
	(= (dataValue htn_bp_controlled_1) 0)
	(= (dataValue htn_bp_controlled_2) 0)
	(= (dataValue htn_bp_controlled_3) 0)

	(initialNode afib_c afib_p1)
	(goalNode afib_c afib_g)
	(initialNode ckd_c ckd_p1)
	(goalNode ckd_c ckd_g)
	(initialNode htn_c htn_p1)
	(goalNode htn_c htn_g)

	(parallelStartNode afib_p1)
	(parallelStartNode afib_p2)
	(parallelEndNode afib_p3)
	(parallelEndNode afib_p4)
	(parallelStartNode ckd_p1)
	(parallelStartNode ckd_p2)
	(parallelStartNode ckd_p3)
	(parallelEndNode ckd_p4)
	(parallelEndNode ckd_p5)
	(parallelEndNode ckd_p6)
	(parallelStartNode htn_p1)
	(parallelStartNode htn_p2)
	(parallelEndNode htn_p3)
	(parallelStartNode htn_p4)
	(parallelEndNode htn_p5)
	(parallelEndNode htn_p6)
	
	(predecessorNode afib_p4 afib_g)
	(predecessorNode afib_d_afib_type afib_a_cardioversion)
	(predecessorNode afib_p1 afib_a_anticoagulation)
	(predecessorNode afib_d_special_circumstances afib_a_rate_control_1)
	(predecessorNode afib_d_symptoms_resolve afib_a_rate_control_maintenance_1)
	(predecessorNode afib_d_symptoms_improve afib_a_rate_control_maintenance_1)
	(predecessorNode afib_d_tachychardia afib_a_rate_control_maintenance_2)
	(predecessorNode afib_d_symptom_recurrence afib_a_rhytm_control_maintenance_1)
	(predecessorNode afib_d_afib_recurs afib_a_rhytm_control_maintenance_2)
	(predecessorNode afib_d_symptom_recurrence afib_a_pill_in_a_pocket)
	(predecessorNode afib_p1 afib_d_special_circumstances)
	(predecessorNode afib_d_special_circumstances afib_d_afib_type)
	(predecessorNode afib_d_symptoms_resolve afib_d_afib_type)
	(predecessorNode afib_d_afib_type afib_d_symptom_recurrence)
	(predecessorNode afib_a_cardioversion afib_d_symptoms_improve)
	(predecessorNode afib_a_rate_control_1 afib_d_symptoms_resolve)
	(predecessorNode afib_p2 afib_d_afib_recurs)
	(predecessorNode afib_p2 afib_d_tachychardia)
	(predecessorNode afib_d_symptoms_improve afib_p2)
	(predecessorNode afib_d1 afib_p3)
	(predecessorNode afib_d2 afib_p3)
	(predecessorNode afib_a_anticoagulation afib_p4)
	(predecessorNode afib_d4 afib_p4)
	(predecessorNode afib_d_tachychardia afib_d1)
	(predecessorNode alt-39999914 afib_d1)
	(predecessorNode afib_d_afib_recurs afib_d2)
	(predecessorNode alt-c9ca60ae afib_d2)
	(predecessorNode afib_a_pill_in_a_pocket afib_d3)
	(predecessorNode alt-37536fba afib_d3)
	(predecessorNode afib_p3 afib_d4)
	(predecessorNode afib_d3 afib_d4)
	(predecessorNode alt-40a95234 afib_d4)
	(predecessorNode ckd_p6 ckd_g)
	(predecessorNode ckd_d_metabolic_abnormality ckd_a_phosphate_binders)
	(predecessorNode ckd_d_hemoglobin_level ckd_a_esa)
	(predecessorNode ckd_d_ferritin_level ckd_a_iron_therapy)
	(predecessorNode ckd_p2 ckd_a_ace_inhibitor)
	(predecessorNode ckd_p2 ckd_a_aspirin)
	(predecessorNode ckd_p2 ckd_a_lifestyle_management)
	(predecessorNode ckd_p1 ckd_d_egfr)
	(predecessorNode ckd_p3 ckd_d_hemoglobin_level)
	(predecessorNode ckd_p3 ckd_d_metabolic_abnormality)
	(predecessorNode ckd_p3 ckd_d_ferritin_level)
	(predecessorNode ckd_p1 ckd_p2)
	(predecessorNode ckd_d_egfr ckd_p3)
	(predecessorNode ckd_d1 ckd_p4)
	(predecessorNode ckd_d2 ckd_p4)
	(predecessorNode ckd_d3 ckd_p4)
	(predecessorNode ckd_a_ace_inhibitor ckd_p5)
	(predecessorNode ckd_a_lifestyle_management ckd_p5)
	(predecessorNode alt-ed39ae97 ckd_p5)
	(predecessorNode ckd_d4 ckd_p6)
	(predecessorNode ckd_p5 ckd_p6)
	(predecessorNode ckd_d_hemoglobin_level ckd_d1)
	(predecessorNode ckd_a_esa ckd_d1)
	(predecessorNode ckd_d_ferritin_level ckd_d2)
	(predecessorNode ckd_a_iron_therapy ckd_d2)
	(predecessorNode ckd_d_metabolic_abnormality ckd_d3)
	(predecessorNode ckd_a_phosphate_binders ckd_d3)
	(predecessorNode ckd_d_egfr ckd_d4)
	(predecessorNode ckd_p4 ckd_d4)
	(predecessorNode htn_p6 htn_g)
	(predecessorNode htn_p1 htn_a_lifestyle_management)
	(predecessorNode htn_d_age_under_55 htn_a_step1_acei)
	(predecessorNode htn_d_age_under_55 htn_a_step1_ccb)
	(predecessorNode htn_p2 htn_a_step2_acei)
	(predecessorNode htn_p2 htn_a_step2_diuretics)
	(predecessorNode htn_p4 htn_a_step3_acei)
	(predecessorNode htn_p4 htn_a_step3_ccb)
	(predecessorNode htn_p4 htn_a_step3_diuretric)
	(predecessorNode htn_d_bp_controlled_3 htn_a_specialist_consult)
	(predecessorNode htn_p1 htn_d_age_under_55)
	(predecessorNode htn_a_step1_acei htn_d_bp_controlled_1)
	(predecessorNode htn_a_step1_ccb htn_d_bp_controlled_1)
	(predecessorNode htn_p3 htn_d_bp_controlled_2)
	(predecessorNode htn_p4 htn_d_bp_controlled_3)
	(predecessorNode htn_d_bp_controlled_1 htn_p2)
	(predecessorNode htn_a_step2_acei htn_p3)
	(predecessorNode htn_a_step2_diuretics htn_p3)
	(predecessorNode htn_d_bp_controlled_2 htn_p4)
	(predecessorNode htn_a_step3_acei htn_p5)
	(predecessorNode htn_a_step3_ccb htn_p5)
	(predecessorNode htn_a_step3_diuretric htn_p5)
	(predecessorNode htn_d1 htn_p5)
	(predecessorNode htn_a_lifestyle_management htn_p6)
	(predecessorNode htn_d3 htn_p6)
	(predecessorNode htn_d_bp_controlled_3 htn_d1)
	(predecessorNode htn_a_specialist_consult htn_d1)
	(predecessorNode htn_p5 htn_d2)
	(predecessorNode htn_d_bp_controlled_2 htn_d2)
	(predecessorNode htn_d_bp_controlled_1 htn_d3)
	(predecessorNode htn_d2 htn_d3)
	(predecessorNode afib_d_symptoms_resolve rev-dummy-1)
	(predecessorNode afib_d_symptoms_improve rev-dummy-1)
	(predecessorNode rev-dummy-1 alt-40a95234)
	(predecessorNode afib_a_rate_control_maintenance_1 alt-40a95234)
	(predecessorNode afib_d_tachychardia rev-dummy-2)
	(predecessorNode rev-dummy-2 alt-39999914)
	(predecessorNode afib_a_rate_control_maintenance_2 alt-39999914)
	(predecessorNode afib_d_symptom_recurrence rev-afib-scb-1)
	(predecessorNode rev-afib-scb-1 alt-37536fba)
	(predecessorNode afib_a_rhytm_control_maintenance_1 alt-37536fba)
	(predecessorNode afib_d_afib_recurs rev-afib-scb-2)
	(predecessorNode rev-afib-scb-2 alt-c9ca60ae)
	(predecessorNode afib_a_rhytm_control_maintenance_2 alt-c9ca60ae)
	(predecessorNode ckd_p2 rev-ckd-warfarin)
	(predecessorNode rev-ckd-warfarin alt-ed39ae97)
	(predecessorNode alt-b0ef3768 alt-ed39ae97)
	(predecessorNode ckd_p2 rev-ckd-doac)
	(predecessorNode rev-ckd-doac alt-b0ef3768)
	(predecessorNode ckd_a_aspirin alt-b0ef3768)

	(actionNode afib_a_cardioversion)
	(actionNode afib_a_anticoagulation)
	(actionNode afib_a_rate_control_1)
	(actionNode afib_a_rate_control_maintenance_1)
	(actionNode afib_a_rate_control_maintenance_2)
	(actionNode afib_a_rhytm_control_maintenance_1)
	(actionNode afib_a_rhytm_control_maintenance_2)
	(actionNode afib_a_pill_in_a_pocket)
	(decisionNode afib_d_special_circumstances)
	(decisionNode afib_d_afib_type)
	(decisionNode afib_d_symptom_recurrence)
	(decisionNode afib_d_symptoms_improve)
	(decisionNode afib_d_symptoms_resolve)
	(decisionNode afib_d_afib_recurs)
	(decisionNode afib_d_tachychardia)
	(dummyNode afib_d1)
	(dummyNode afib_d2)
	(dummyNode afib_d3)
	(dummyNode afib_d4)
	(actionNode ckd_a_phosphate_binders)
	(actionNode ckd_a_esa)
	(actionNode ckd_a_iron_therapy)
	(actionNode ckd_a_ace_inhibitor)
	(actionNode ckd_a_aspirin)
	(actionNode ckd_a_lifestyle_management)
	(decisionNode ckd_d_egfr)
	(decisionNode ckd_d_hemoglobin_level)
	(decisionNode ckd_d_metabolic_abnormality)
	(decisionNode ckd_d_ferritin_level)
	(dummyNode ckd_d1)
	(dummyNode ckd_d2)
	(dummyNode ckd_d3)
	(dummyNode ckd_d4)
	(actionNode htn_a_lifestyle_management)
	(actionNode htn_a_step1_acei)
	(actionNode htn_a_step1_ccb)
	(actionNode htn_a_step2_acei)
	(actionNode htn_a_step2_diuretics)
	(actionNode htn_a_step3_acei)
	(actionNode htn_a_step3_ccb)
	(actionNode htn_a_step3_diuretric)
	(actionNode htn_a_specialist_consult)
	(decisionNode htn_d_age_under_55)
	(decisionNode htn_d_bp_controlled_1)
	(decisionNode htn_d_bp_controlled_2)
	(decisionNode htn_d_bp_controlled_3)
	(dummyNode htn_d1)
	(dummyNode htn_d2)
	(dummyNode htn_d3)
	(dummyNode rev-dummy-1)
	(dummyNode alt-40a95234)
	(dummyNode rev-dummy-2)
	(dummyNode alt-39999914)
	(actionNode rev-afib-scb-1)
	(dummyNode alt-37536fba)
	(actionNode rev-afib-scb-2)
	(dummyNode alt-c9ca60ae)
	(actionNode rev-ckd-warfarin)
	(dummyNode alt-ed39ae97)
	(actionNode rev-ckd-doac)
	(dummyNode alt-b0ef3768)

	(originalAction afib_a_cardioversion)
	(originalAction afib_a_anticoagulation)
	(originalAction afib_a_rate_control_1)
	(originalAction afib_a_rate_control_maintenance_1)
	(originalAction afib_a_rate_control_maintenance_2)
	(originalAction afib_a_rhytm_control_maintenance_1)
	(originalAction afib_a_rhytm_control_maintenance_2)
	(originalAction afib_a_pill_in_a_pocket)
	(originalAction ckd_a_phosphate_binders)
	(originalAction ckd_a_esa)
	(originalAction ckd_a_iron_therapy)
	(originalAction ckd_a_ace_inhibitor)
	(originalAction ckd_a_aspirin)
	(originalAction ckd_a_lifestyle_management)
	(originalAction htn_a_lifestyle_management)
	(originalAction htn_a_step1_acei)
	(originalAction htn_a_step1_ccb)
	(originalAction htn_a_step2_acei)
	(originalAction htn_a_step2_diuretics)
	(originalAction htn_a_step3_acei)
	(originalAction htn_a_step3_ccb)
	(originalAction htn_a_step3_diuretric)
	(originalAction htn_a_specialist_consult)

	(revisionAction alt-40a95234 remove-bb-1)
	(revisionAction alt-39999914 remove-bb-2)
	(revisionAction rev-afib-scb-1 replace-cpb-with-scb-1)
	(revisionAction alt-37536fba replace-cpb-with-scb-1)
	(revisionAction rev-afib-scb-2 replace-cpb-with-scb-2)
	(revisionAction alt-c9ca60ae replace-cpb-with-scb-2)
	(revisionAction rev-ckd-warfarin replace-low-dose-aspirin-with-warfarin)
	(revisionAction alt-ed39ae97 replace-low-dose-aspirin-with-warfarin)
	(revisionAction rev-ckd-doac replace-low-dose-aspirin-with-doac)
	(revisionAction alt-b0ef3768 replace-low-dose-aspirin-with-doac)

	(= (revisionFlag afib_g remove-bb-1) 0)
	(= (revisionFlag afib_a_cardioversion remove-bb-1) 0)
	(= (revisionFlag afib_a_anticoagulation remove-bb-1) 0)
	(= (revisionFlag afib_a_rate_control_1 remove-bb-1) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_1 remove-bb-1) 1)
	(= (revisionFlag afib_a_rate_control_maintenance_2 remove-bb-1) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_1 remove-bb-1) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_2 remove-bb-1) 0)
	(= (revisionFlag afib_a_pill_in_a_pocket remove-bb-1) 0)
	(= (revisionFlag afib_d_special_circumstances remove-bb-1) 0)
	(= (revisionFlag afib_d_afib_type remove-bb-1) 0)
	(= (revisionFlag afib_d_symptom_recurrence remove-bb-1) 0)
	(= (revisionFlag afib_d_symptoms_improve remove-bb-1) 0)
	(= (revisionFlag afib_d_symptoms_resolve remove-bb-1) 0)
	(= (revisionFlag afib_d_afib_recurs remove-bb-1) 0)
	(= (revisionFlag afib_d_tachychardia remove-bb-1) 0)
	(= (revisionFlag afib_p1 remove-bb-1) 0)
	(= (revisionFlag afib_p2 remove-bb-1) 0)
	(= (revisionFlag afib_p3 remove-bb-1) 0)
	(= (revisionFlag afib_p4 remove-bb-1) 0)
	(= (revisionFlag afib_d1 remove-bb-1) 0)
	(= (revisionFlag afib_d2 remove-bb-1) 0)
	(= (revisionFlag afib_d3 remove-bb-1) 0)
	(= (revisionFlag afib_d4 remove-bb-1) 0)
	(= (revisionFlag ckd_g remove-bb-1) 0)
	(= (revisionFlag ckd_a_phosphate_binders remove-bb-1) 0)
	(= (revisionFlag ckd_a_esa remove-bb-1) 0)
	(= (revisionFlag ckd_a_iron_therapy remove-bb-1) 0)
	(= (revisionFlag ckd_a_ace_inhibitor remove-bb-1) 0)
	(= (revisionFlag ckd_a_aspirin remove-bb-1) 0)
	(= (revisionFlag ckd_a_lifestyle_management remove-bb-1) 0)
	(= (revisionFlag ckd_d_egfr remove-bb-1) 0)
	(= (revisionFlag ckd_d_hemoglobin_level remove-bb-1) 0)
	(= (revisionFlag ckd_d_metabolic_abnormality remove-bb-1) 0)
	(= (revisionFlag ckd_d_ferritin_level remove-bb-1) 0)
	(= (revisionFlag ckd_p1 remove-bb-1) 0)
	(= (revisionFlag ckd_p2 remove-bb-1) 0)
	(= (revisionFlag ckd_p3 remove-bb-1) 0)
	(= (revisionFlag ckd_p4 remove-bb-1) 0)
	(= (revisionFlag ckd_p5 remove-bb-1) 0)
	(= (revisionFlag ckd_p6 remove-bb-1) 0)
	(= (revisionFlag ckd_d1 remove-bb-1) 0)
	(= (revisionFlag ckd_d2 remove-bb-1) 0)
	(= (revisionFlag ckd_d3 remove-bb-1) 0)
	(= (revisionFlag ckd_d4 remove-bb-1) 0)
	(= (revisionFlag htn_g remove-bb-1) 0)
	(= (revisionFlag htn_a_lifestyle_management remove-bb-1) 0)
	(= (revisionFlag htn_a_step1_acei remove-bb-1) 0)
	(= (revisionFlag htn_a_step1_ccb remove-bb-1) 0)
	(= (revisionFlag htn_a_step2_acei remove-bb-1) 0)
	(= (revisionFlag htn_a_step2_diuretics remove-bb-1) 0)
	(= (revisionFlag htn_a_step3_acei remove-bb-1) 0)
	(= (revisionFlag htn_a_step3_ccb remove-bb-1) 0)
	(= (revisionFlag htn_a_step3_diuretric remove-bb-1) 0)
	(= (revisionFlag htn_a_specialist_consult remove-bb-1) 0)
	(= (revisionFlag htn_d_age_under_55 remove-bb-1) 0)
	(= (revisionFlag htn_d_bp_controlled_1 remove-bb-1) 0)
	(= (revisionFlag htn_d_bp_controlled_2 remove-bb-1) 0)
	(= (revisionFlag htn_d_bp_controlled_3 remove-bb-1) 0)
	(= (revisionFlag htn_p1 remove-bb-1) 0)
	(= (revisionFlag htn_p2 remove-bb-1) 0)
	(= (revisionFlag htn_p3 remove-bb-1) 0)
	(= (revisionFlag htn_p4 remove-bb-1) 0)
	(= (revisionFlag htn_p5 remove-bb-1) 0)
	(= (revisionFlag htn_p6 remove-bb-1) 0)
	(= (revisionFlag htn_d1 remove-bb-1) 0)
	(= (revisionFlag htn_d2 remove-bb-1) 0)
	(= (revisionFlag htn_d3 remove-bb-1) 0)
	(= (revisionFlag rev-dummy-1 remove-bb-1) 0)
	(= (revisionFlag alt-40a95234 remove-bb-1) 0)
	(= (revisionFlag rev-dummy-2 remove-bb-1) 0)
	(= (revisionFlag alt-39999914 remove-bb-1) 0)
	(= (revisionFlag rev-afib-scb-1 remove-bb-1) 0)
	(= (revisionFlag alt-37536fba remove-bb-1) 0)
	(= (revisionFlag rev-afib-scb-2 remove-bb-1) 0)
	(= (revisionFlag alt-c9ca60ae remove-bb-1) 0)
	(= (revisionFlag rev-ckd-warfarin remove-bb-1) 0)
	(= (revisionFlag alt-ed39ae97 remove-bb-1) 0)
	(= (revisionFlag rev-ckd-doac remove-bb-1) 0)
	(= (revisionFlag alt-b0ef3768 remove-bb-1) 0)

	(= (revisionSequenceNumNodes remove-bb-1) 1)
	(= (numNodesToReplace remove-bb-1) 1)
	(= (revisionCount remove-bb-1) 0)
	(= (revisionIDPass afib_c remove-bb-1) 0)
	(= (revisionIDPass ckd_c remove-bb-1) 0)
	(= (revisionIDPass htn_c remove-bb-1) 0)

	(= (revisionFlag afib_g remove-bb-2) 0)
	(= (revisionFlag afib_a_cardioversion remove-bb-2) 0)
	(= (revisionFlag afib_a_anticoagulation remove-bb-2) 0)
	(= (revisionFlag afib_a_rate_control_1 remove-bb-2) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_1 remove-bb-2) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_2 remove-bb-2) 1)
	(= (revisionFlag afib_a_rhytm_control_maintenance_1 remove-bb-2) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_2 remove-bb-2) 0)
	(= (revisionFlag afib_a_pill_in_a_pocket remove-bb-2) 0)
	(= (revisionFlag afib_d_special_circumstances remove-bb-2) 0)
	(= (revisionFlag afib_d_afib_type remove-bb-2) 0)
	(= (revisionFlag afib_d_symptom_recurrence remove-bb-2) 0)
	(= (revisionFlag afib_d_symptoms_improve remove-bb-2) 0)
	(= (revisionFlag afib_d_symptoms_resolve remove-bb-2) 0)
	(= (revisionFlag afib_d_afib_recurs remove-bb-2) 0)
	(= (revisionFlag afib_d_tachychardia remove-bb-2) 0)
	(= (revisionFlag afib_p1 remove-bb-2) 0)
	(= (revisionFlag afib_p2 remove-bb-2) 0)
	(= (revisionFlag afib_p3 remove-bb-2) 0)
	(= (revisionFlag afib_p4 remove-bb-2) 0)
	(= (revisionFlag afib_d1 remove-bb-2) 0)
	(= (revisionFlag afib_d2 remove-bb-2) 0)
	(= (revisionFlag afib_d3 remove-bb-2) 0)
	(= (revisionFlag afib_d4 remove-bb-2) 0)
	(= (revisionFlag ckd_g remove-bb-2) 0)
	(= (revisionFlag ckd_a_phosphate_binders remove-bb-2) 0)
	(= (revisionFlag ckd_a_esa remove-bb-2) 0)
	(= (revisionFlag ckd_a_iron_therapy remove-bb-2) 0)
	(= (revisionFlag ckd_a_ace_inhibitor remove-bb-2) 0)
	(= (revisionFlag ckd_a_aspirin remove-bb-2) 0)
	(= (revisionFlag ckd_a_lifestyle_management remove-bb-2) 0)
	(= (revisionFlag ckd_d_egfr remove-bb-2) 0)
	(= (revisionFlag ckd_d_hemoglobin_level remove-bb-2) 0)
	(= (revisionFlag ckd_d_metabolic_abnormality remove-bb-2) 0)
	(= (revisionFlag ckd_d_ferritin_level remove-bb-2) 0)
	(= (revisionFlag ckd_p1 remove-bb-2) 0)
	(= (revisionFlag ckd_p2 remove-bb-2) 0)
	(= (revisionFlag ckd_p3 remove-bb-2) 0)
	(= (revisionFlag ckd_p4 remove-bb-2) 0)
	(= (revisionFlag ckd_p5 remove-bb-2) 0)
	(= (revisionFlag ckd_p6 remove-bb-2) 0)
	(= (revisionFlag ckd_d1 remove-bb-2) 0)
	(= (revisionFlag ckd_d2 remove-bb-2) 0)
	(= (revisionFlag ckd_d3 remove-bb-2) 0)
	(= (revisionFlag ckd_d4 remove-bb-2) 0)
	(= (revisionFlag htn_g remove-bb-2) 0)
	(= (revisionFlag htn_a_lifestyle_management remove-bb-2) 0)
	(= (revisionFlag htn_a_step1_acei remove-bb-2) 0)
	(= (revisionFlag htn_a_step1_ccb remove-bb-2) 0)
	(= (revisionFlag htn_a_step2_acei remove-bb-2) 0)
	(= (revisionFlag htn_a_step2_diuretics remove-bb-2) 0)
	(= (revisionFlag htn_a_step3_acei remove-bb-2) 0)
	(= (revisionFlag htn_a_step3_ccb remove-bb-2) 0)
	(= (revisionFlag htn_a_step3_diuretric remove-bb-2) 0)
	(= (revisionFlag htn_a_specialist_consult remove-bb-2) 0)
	(= (revisionFlag htn_d_age_under_55 remove-bb-2) 0)
	(= (revisionFlag htn_d_bp_controlled_1 remove-bb-2) 0)
	(= (revisionFlag htn_d_bp_controlled_2 remove-bb-2) 0)
	(= (revisionFlag htn_d_bp_controlled_3 remove-bb-2) 0)
	(= (revisionFlag htn_p1 remove-bb-2) 0)
	(= (revisionFlag htn_p2 remove-bb-2) 0)
	(= (revisionFlag htn_p3 remove-bb-2) 0)
	(= (revisionFlag htn_p4 remove-bb-2) 0)
	(= (revisionFlag htn_p5 remove-bb-2) 0)
	(= (revisionFlag htn_p6 remove-bb-2) 0)
	(= (revisionFlag htn_d1 remove-bb-2) 0)
	(= (revisionFlag htn_d2 remove-bb-2) 0)
	(= (revisionFlag htn_d3 remove-bb-2) 0)
	(= (revisionFlag rev-dummy-1 remove-bb-2) 0)
	(= (revisionFlag alt-40a95234 remove-bb-2) 0)
	(= (revisionFlag rev-dummy-2 remove-bb-2) 0)
	(= (revisionFlag alt-39999914 remove-bb-2) 0)
	(= (revisionFlag rev-afib-scb-1 remove-bb-2) 0)
	(= (revisionFlag alt-37536fba remove-bb-2) 0)
	(= (revisionFlag rev-afib-scb-2 remove-bb-2) 0)
	(= (revisionFlag alt-c9ca60ae remove-bb-2) 0)
	(= (revisionFlag rev-ckd-warfarin remove-bb-2) 0)
	(= (revisionFlag alt-ed39ae97 remove-bb-2) 0)
	(= (revisionFlag rev-ckd-doac remove-bb-2) 0)
	(= (revisionFlag alt-b0ef3768 remove-bb-2) 0)

	(= (revisionSequenceNumNodes remove-bb-2) 1)
	(= (numNodesToReplace remove-bb-2) 1)
	(= (revisionCount remove-bb-2) 0)
	(= (revisionIDPass afib_c remove-bb-2) 0)
	(= (revisionIDPass ckd_c remove-bb-2) 0)
	(= (revisionIDPass htn_c remove-bb-2) 0)

	(= (revisionFlag afib_g replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_a_cardioversion replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_a_anticoagulation replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_a_rate_control_1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_1 replace-cpb-with-scb-1) 1)
	(= (revisionFlag afib_a_rhytm_control_maintenance_2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_a_pill_in_a_pocket replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d_special_circumstances replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d_afib_type replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d_symptom_recurrence replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d_symptoms_improve replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d_symptoms_resolve replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d_afib_recurs replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d_tachychardia replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_p1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_p2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_p3 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_p4 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d3 replace-cpb-with-scb-1) 0)
	(= (revisionFlag afib_d4 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_g replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_a_phosphate_binders replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_a_esa replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_a_iron_therapy replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_a_ace_inhibitor replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_a_aspirin replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_a_lifestyle_management replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d_egfr replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d_hemoglobin_level replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d_metabolic_abnormality replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d_ferritin_level replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_p1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_p2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_p3 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_p4 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_p5 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_p6 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d3 replace-cpb-with-scb-1) 0)
	(= (revisionFlag ckd_d4 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_g replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_lifestyle_management replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_step1_acei replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_step1_ccb replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_step2_acei replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_step2_diuretics replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_step3_acei replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_step3_ccb replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_step3_diuretric replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_a_specialist_consult replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_d_age_under_55 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_d_bp_controlled_1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_d_bp_controlled_2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_d_bp_controlled_3 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_p1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_p2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_p3 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_p4 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_p5 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_p6 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_d1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_d2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag htn_d3 replace-cpb-with-scb-1) 0)
	(= (revisionFlag rev-dummy-1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag alt-40a95234 replace-cpb-with-scb-1) 0)
	(= (revisionFlag rev-dummy-2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag alt-39999914 replace-cpb-with-scb-1) 0)
	(= (revisionFlag rev-afib-scb-1 replace-cpb-with-scb-1) 0)
	(= (revisionFlag alt-37536fba replace-cpb-with-scb-1) 0)
	(= (revisionFlag rev-afib-scb-2 replace-cpb-with-scb-1) 0)
	(= (revisionFlag alt-c9ca60ae replace-cpb-with-scb-1) 0)
	(= (revisionFlag rev-ckd-warfarin replace-cpb-with-scb-1) 0)
	(= (revisionFlag alt-ed39ae97 replace-cpb-with-scb-1) 0)
	(= (revisionFlag rev-ckd-doac replace-cpb-with-scb-1) 0)
	(= (revisionFlag alt-b0ef3768 replace-cpb-with-scb-1) 0)

	(= (revisionSequenceNumNodes replace-cpb-with-scb-1) 1)
	(= (numNodesToReplace replace-cpb-with-scb-1) 1)
	(= (revisionCount replace-cpb-with-scb-1) 0)
	(= (revisionIDPass afib_c replace-cpb-with-scb-1) 0)
	(= (revisionIDPass ckd_c replace-cpb-with-scb-1) 0)
	(= (revisionIDPass htn_c replace-cpb-with-scb-1) 0)

	(= (revisionFlag afib_g replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_a_cardioversion replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_a_anticoagulation replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_a_rate_control_1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_2 replace-cpb-with-scb-2) 1)
	(= (revisionFlag afib_a_pill_in_a_pocket replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d_special_circumstances replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d_afib_type replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d_symptom_recurrence replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d_symptoms_improve replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d_symptoms_resolve replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d_afib_recurs replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d_tachychardia replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_p1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_p2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_p3 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_p4 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d3 replace-cpb-with-scb-2) 0)
	(= (revisionFlag afib_d4 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_g replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_a_phosphate_binders replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_a_esa replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_a_iron_therapy replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_a_ace_inhibitor replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_a_aspirin replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_a_lifestyle_management replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d_egfr replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d_hemoglobin_level replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d_metabolic_abnormality replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d_ferritin_level replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_p1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_p2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_p3 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_p4 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_p5 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_p6 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d3 replace-cpb-with-scb-2) 0)
	(= (revisionFlag ckd_d4 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_g replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_lifestyle_management replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_step1_acei replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_step1_ccb replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_step2_acei replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_step2_diuretics replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_step3_acei replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_step3_ccb replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_step3_diuretric replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_a_specialist_consult replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_d_age_under_55 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_d_bp_controlled_1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_d_bp_controlled_2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_d_bp_controlled_3 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_p1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_p2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_p3 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_p4 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_p5 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_p6 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_d1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_d2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag htn_d3 replace-cpb-with-scb-2) 0)
	(= (revisionFlag rev-dummy-1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag alt-40a95234 replace-cpb-with-scb-2) 0)
	(= (revisionFlag rev-dummy-2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag alt-39999914 replace-cpb-with-scb-2) 0)
	(= (revisionFlag rev-afib-scb-1 replace-cpb-with-scb-2) 0)
	(= (revisionFlag alt-37536fba replace-cpb-with-scb-2) 0)
	(= (revisionFlag rev-afib-scb-2 replace-cpb-with-scb-2) 0)
	(= (revisionFlag alt-c9ca60ae replace-cpb-with-scb-2) 0)
	(= (revisionFlag rev-ckd-warfarin replace-cpb-with-scb-2) 0)
	(= (revisionFlag alt-ed39ae97 replace-cpb-with-scb-2) 0)
	(= (revisionFlag rev-ckd-doac replace-cpb-with-scb-2) 0)
	(= (revisionFlag alt-b0ef3768 replace-cpb-with-scb-2) 0)

	(= (revisionSequenceNumNodes replace-cpb-with-scb-2) 1)
	(= (numNodesToReplace replace-cpb-with-scb-2) 1)
	(= (revisionCount replace-cpb-with-scb-2) 0)
	(= (revisionIDPass afib_c replace-cpb-with-scb-2) 0)
	(= (revisionIDPass ckd_c replace-cpb-with-scb-2) 0)
	(= (revisionIDPass htn_c replace-cpb-with-scb-2) 0)

	(= (revisionFlag afib_g replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_cardioversion replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_anticoagulation replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_rate_control_1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_a_pill_in_a_pocket replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d_special_circumstances replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d_afib_type replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d_symptom_recurrence replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d_symptoms_improve replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d_symptoms_resolve replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d_afib_recurs replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d_tachychardia replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_p1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_p2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_p3 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_p4 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d3 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag afib_d4 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_g replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_a_phosphate_binders replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_a_esa replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_a_iron_therapy replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_a_ace_inhibitor replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_a_aspirin replace-low-dose-aspirin-with-warfarin) 1)
	(= (revisionFlag ckd_a_lifestyle_management replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d_egfr replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d_hemoglobin_level replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d_metabolic_abnormality replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d_ferritin_level replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_p1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_p2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_p3 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_p4 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_p5 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_p6 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d3 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag ckd_d4 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_g replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_lifestyle_management replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_step1_acei replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_step1_ccb replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_step2_acei replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_step2_diuretics replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_step3_acei replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_step3_ccb replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_step3_diuretric replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_a_specialist_consult replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_d_age_under_55 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_d_bp_controlled_1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_d_bp_controlled_2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_d_bp_controlled_3 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_p1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_p2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_p3 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_p4 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_p5 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_p6 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_d1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_d2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag htn_d3 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag rev-dummy-1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag alt-40a95234 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag rev-dummy-2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag alt-39999914 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag rev-afib-scb-1 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag alt-37536fba replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag rev-afib-scb-2 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag alt-c9ca60ae replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag rev-ckd-warfarin replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag alt-ed39ae97 replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag rev-ckd-doac replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionFlag alt-b0ef3768 replace-low-dose-aspirin-with-warfarin) 0)

	(= (revisionSequenceNumNodes replace-low-dose-aspirin-with-warfarin) 1)
	(= (numNodesToReplace replace-low-dose-aspirin-with-warfarin) 1)
	(= (revisionCount replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionIDPass afib_c replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionIDPass ckd_c replace-low-dose-aspirin-with-warfarin) 0)
	(= (revisionIDPass htn_c replace-low-dose-aspirin-with-warfarin) 0)

	(= (revisionFlag afib_g replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_cardioversion replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_anticoagulation replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_rate_control_1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_rate_control_maintenance_2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_rhytm_control_maintenance_2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_a_pill_in_a_pocket replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d_special_circumstances replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d_afib_type replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d_symptom_recurrence replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d_symptoms_improve replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d_symptoms_resolve replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d_afib_recurs replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d_tachychardia replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_p1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_p2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_p3 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_p4 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d3 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag afib_d4 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_g replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_a_phosphate_binders replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_a_esa replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_a_iron_therapy replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_a_ace_inhibitor replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_a_aspirin replace-low-dose-aspirin-with-doac) 1)
	(= (revisionFlag ckd_a_lifestyle_management replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d_egfr replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d_hemoglobin_level replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d_metabolic_abnormality replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d_ferritin_level replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_p1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_p2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_p3 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_p4 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_p5 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_p6 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d3 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag ckd_d4 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_g replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_lifestyle_management replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_step1_acei replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_step1_ccb replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_step2_acei replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_step2_diuretics replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_step3_acei replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_step3_ccb replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_step3_diuretric replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_a_specialist_consult replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_d_age_under_55 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_d_bp_controlled_1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_d_bp_controlled_2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_d_bp_controlled_3 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_p1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_p2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_p3 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_p4 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_p5 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_p6 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_d1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_d2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag htn_d3 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag rev-dummy-1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag alt-40a95234 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag rev-dummy-2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag alt-39999914 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag rev-afib-scb-1 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag alt-37536fba replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag rev-afib-scb-2 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag alt-c9ca60ae replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag rev-ckd-warfarin replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag alt-ed39ae97 replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag rev-ckd-doac replace-low-dose-aspirin-with-doac) 0)
	(= (revisionFlag alt-b0ef3768 replace-low-dose-aspirin-with-doac) 0)

	(= (revisionSequenceNumNodes replace-low-dose-aspirin-with-doac) 1)
	(= (numNodesToReplace replace-low-dose-aspirin-with-doac) 1)
	(= (revisionCount replace-low-dose-aspirin-with-doac) 0)
	(= (revisionIDPass afib_c replace-low-dose-aspirin-with-doac) 0)
	(= (revisionIDPass ckd_c replace-low-dose-aspirin-with-doac) 0)
	(= (revisionIDPass htn_c replace-low-dose-aspirin-with-doac) 0)


	(= (allRevisionsPass afib_c) 0)
	(= (allRevisionsPass ckd_c) 0)
	(= (allRevisionsPass htn_c) 0)
	(= (numRevisionIDs afib_c) 4)
	(= (numRevisionIDs ckd_c) 2)
	(= (numRevisionIDs htn_c) 0)

	(anyRevisionOps ckd_c)
	(anyRevisionOps afib_c)
	(noRevisionOps htn_c)

	(= (tentativeGoalCount) 0)

	(= (numGoals) 3)

	(= (nodeCost afib_g) 0)
	(= (nodeCost afib_a_cardioversion) 0)
	(= (nodeCost afib_a_anticoagulation) 0)
	(= (nodeCost afib_a_rate_control_1) 0)
	(= (nodeCost afib_a_rate_control_maintenance_1) 0)
	(= (nodeCost afib_a_rate_control_maintenance_2) 0)
	(= (nodeCost afib_a_rhytm_control_maintenance_1) 0)
	(= (nodeCost afib_a_rhytm_control_maintenance_2) 0)
	(= (nodeCost afib_a_pill_in_a_pocket) 0)
	(= (nodeCost afib_d_special_circumstances) 0)
	(= (nodeCost afib_d_afib_type) 0)
	(= (nodeCost afib_d_symptom_recurrence) 0)
	(= (nodeCost afib_d_symptoms_improve) 0)
	(= (nodeCost afib_d_symptoms_resolve) 0)
	(= (nodeCost afib_d_afib_recurs) 0)
	(= (nodeCost afib_d_tachychardia) 0)
	(= (nodeCost afib_p1) 0)
	(= (nodeCost afib_p2) 0)
	(= (nodeCost afib_p3) 0)
	(= (nodeCost afib_p4) 0)
	(= (nodeCost afib_d1) 0)
	(= (nodeCost afib_d2) 0)
	(= (nodeCost afib_d3) 0)
	(= (nodeCost afib_d4) 0)
	(= (nodeCost ckd_g) 0)
	(= (nodeCost ckd_a_phosphate_binders) 0)
	(= (nodeCost ckd_a_esa) 0)
	(= (nodeCost ckd_a_iron_therapy) 0)
	(= (nodeCost ckd_a_ace_inhibitor) 0)
	(= (nodeCost ckd_a_aspirin) 0)
	(= (nodeCost ckd_a_lifestyle_management) 0)
	(= (nodeCost ckd_d_egfr) 0)
	(= (nodeCost ckd_d_hemoglobin_level) 0)
	(= (nodeCost ckd_d_metabolic_abnormality) 0)
	(= (nodeCost ckd_d_ferritin_level) 0)
	(= (nodeCost ckd_p1) 0)
	(= (nodeCost ckd_p2) 0)
	(= (nodeCost ckd_p3) 0)
	(= (nodeCost ckd_p4) 0)
	(= (nodeCost ckd_p5) 0)
	(= (nodeCost ckd_p6) 0)
	(= (nodeCost ckd_d1) 0)
	(= (nodeCost ckd_d2) 0)
	(= (nodeCost ckd_d3) 0)
	(= (nodeCost ckd_d4) 0)
	(= (nodeCost htn_g) 0)
	(= (nodeCost htn_a_lifestyle_management) 0)
	(= (nodeCost htn_a_step1_acei) 0)
	(= (nodeCost htn_a_step1_ccb) 0)
	(= (nodeCost htn_a_step2_acei) 0)
	(= (nodeCost htn_a_step2_diuretics) 0)
	(= (nodeCost htn_a_step3_acei) 0)
	(= (nodeCost htn_a_step3_ccb) 0)
	(= (nodeCost htn_a_step3_diuretric) 0)
	(= (nodeCost htn_a_specialist_consult) 0)
	(= (nodeCost htn_d_age_under_55) 0)
	(= (nodeCost htn_d_bp_controlled_1) 0)
	(= (nodeCost htn_d_bp_controlled_2) 0)
	(= (nodeCost htn_d_bp_controlled_3) 0)
	(= (nodeCost htn_p1) 0)
	(= (nodeCost htn_p2) 0)
	(= (nodeCost htn_p3) 0)
	(= (nodeCost htn_p4) 0)
	(= (nodeCost htn_p5) 0)
	(= (nodeCost htn_p6) 0)
	(= (nodeCost htn_d1) 0)
	(= (nodeCost htn_d2) 0)
	(= (nodeCost htn_d3) 0)
	(= (nodeCost rev-dummy-1) 100)
	(= (nodeCost alt-40a95234) 0)
	(= (nodeCost rev-dummy-2) 100)
	(= (nodeCost alt-39999914) 0)
	(= (nodeCost rev-afib-scb-1) 100)
	(= (nodeCost alt-37536fba) 0)
	(= (nodeCost rev-afib-scb-2) 100)
	(= (nodeCost alt-c9ca60ae) 0)
	(= (nodeCost rev-ckd-warfarin) 100)
	(= (nodeCost alt-ed39ae97) 0)
	(= (nodeCost rev-ckd-doac) 100)
	(= (nodeCost alt-b0ef3768) 0)

	(= (nodeExecCost afib_g) 0)
	(= (nodeExecCost afib_a_cardioversion) 0)
	(= (nodeExecCost afib_a_anticoagulation) 0)
	(= (nodeExecCost afib_a_rate_control_1) 0)
	(= (nodeExecCost afib_a_rate_control_maintenance_1) 0)
	(= (nodeExecCost afib_a_rate_control_maintenance_2) 0)
	(= (nodeExecCost afib_a_rhytm_control_maintenance_1) 0)
	(= (nodeExecCost afib_a_rhytm_control_maintenance_2) 0)
	(= (nodeExecCost afib_a_pill_in_a_pocket) 0)
	(= (nodeExecCost afib_d_special_circumstances) 0)
	(= (nodeExecCost afib_d_afib_type) 0)
	(= (nodeExecCost afib_d_symptom_recurrence) 0)
	(= (nodeExecCost afib_d_symptoms_improve) 0)
	(= (nodeExecCost afib_d_symptoms_resolve) 0)
	(= (nodeExecCost afib_d_afib_recurs) 0)
	(= (nodeExecCost afib_d_tachychardia) 0)
	(= (nodeExecCost afib_p1) 0)
	(= (nodeExecCost afib_p2) 0)
	(= (nodeExecCost afib_p3) 0)
	(= (nodeExecCost afib_p4) 0)
	(= (nodeExecCost afib_d1) 0)
	(= (nodeExecCost afib_d2) 0)
	(= (nodeExecCost afib_d3) 0)
	(= (nodeExecCost afib_d4) 0)
	(= (nodeExecCost ckd_g) 0)
	(= (nodeExecCost ckd_a_phosphate_binders) 0)
	(= (nodeExecCost ckd_a_esa) 0)
	(= (nodeExecCost ckd_a_iron_therapy) 0)
	(= (nodeExecCost ckd_a_ace_inhibitor) 0)
	(= (nodeExecCost ckd_a_aspirin) 0)
	(= (nodeExecCost ckd_a_lifestyle_management) 0)
	(= (nodeExecCost ckd_d_egfr) 0)
	(= (nodeExecCost ckd_d_hemoglobin_level) 0)
	(= (nodeExecCost ckd_d_metabolic_abnormality) 0)
	(= (nodeExecCost ckd_d_ferritin_level) 0)
	(= (nodeExecCost ckd_p1) 0)
	(= (nodeExecCost ckd_p2) 0)
	(= (nodeExecCost ckd_p3) 0)
	(= (nodeExecCost ckd_p4) 0)
	(= (nodeExecCost ckd_p5) 0)
	(= (nodeExecCost ckd_p6) 0)
	(= (nodeExecCost ckd_d1) 0)
	(= (nodeExecCost ckd_d2) 0)
	(= (nodeExecCost ckd_d3) 0)
	(= (nodeExecCost ckd_d4) 0)
	(= (nodeExecCost htn_g) 0)
	(= (nodeExecCost htn_a_lifestyle_management) 0)
	(= (nodeExecCost htn_a_step1_acei) 0)
	(= (nodeExecCost htn_a_step1_ccb) 0)
	(= (nodeExecCost htn_a_step2_acei) 0)
	(= (nodeExecCost htn_a_step2_diuretics) 0)
	(= (nodeExecCost htn_a_step3_acei) 0)
	(= (nodeExecCost htn_a_step3_ccb) 0)
	(= (nodeExecCost htn_a_step3_diuretric) 0)
	(= (nodeExecCost htn_a_specialist_consult) 0)
	(= (nodeExecCost htn_d_age_under_55) 0)
	(= (nodeExecCost htn_d_bp_controlled_1) 0)
	(= (nodeExecCost htn_d_bp_controlled_2) 0)
	(= (nodeExecCost htn_d_bp_controlled_3) 0)
	(= (nodeExecCost htn_p1) 0)
	(= (nodeExecCost htn_p2) 0)
	(= (nodeExecCost htn_p3) 0)
	(= (nodeExecCost htn_p4) 0)
	(= (nodeExecCost htn_p5) 0)
	(= (nodeExecCost htn_p6) 0)
	(= (nodeExecCost htn_d1) 0)
	(= (nodeExecCost htn_d2) 0)
	(= (nodeExecCost htn_d3) 0)
	(= (nodeExecCost rev-dummy-1) 0)
	(= (nodeExecCost alt-40a95234) 0)
	(= (nodeExecCost rev-dummy-2) 0)
	(= (nodeExecCost alt-39999914) 0)
	(= (nodeExecCost rev-afib-scb-1) 0)
	(= (nodeExecCost alt-37536fba) 0)
	(= (nodeExecCost rev-afib-scb-2) 0)
	(= (nodeExecCost alt-c9ca60ae) 0)
	(= (nodeExecCost rev-ckd-warfarin) 0)
	(= (nodeExecCost alt-ed39ae97) 0)
	(= (nodeExecCost rev-ckd-doac) 0)
	(= (nodeExecCost alt-b0ef3768) 0)

	(= (nodeBurden afib_g) 0)
	(= (nodeBurden afib_a_cardioversion) 0)
	(= (nodeBurden afib_a_anticoagulation) 0)
	(= (nodeBurden afib_a_rate_control_1) 0)
	(= (nodeBurden afib_a_rate_control_maintenance_1) 0)
	(= (nodeBurden afib_a_rate_control_maintenance_2) 0)
	(= (nodeBurden afib_a_rhytm_control_maintenance_1) 0)
	(= (nodeBurden afib_a_rhytm_control_maintenance_2) 0)
	(= (nodeBurden afib_a_pill_in_a_pocket) 0)
	(= (nodeBurden afib_d_special_circumstances) 0)
	(= (nodeBurden afib_d_afib_type) 0)
	(= (nodeBurden afib_d_symptom_recurrence) 0)
	(= (nodeBurden afib_d_symptoms_improve) 0)
	(= (nodeBurden afib_d_symptoms_resolve) 0)
	(= (nodeBurden afib_d_afib_recurs) 0)
	(= (nodeBurden afib_d_tachychardia) 0)
	(= (nodeBurden afib_p1) 0)
	(= (nodeBurden afib_p2) 0)
	(= (nodeBurden afib_p3) 0)
	(= (nodeBurden afib_p4) 0)
	(= (nodeBurden afib_d1) 0)
	(= (nodeBurden afib_d2) 0)
	(= (nodeBurden afib_d3) 0)
	(= (nodeBurden afib_d4) 0)
	(= (nodeBurden ckd_g) 0)
	(= (nodeBurden ckd_a_phosphate_binders) 0)
	(= (nodeBurden ckd_a_esa) 0)
	(= (nodeBurden ckd_a_iron_therapy) 0)
	(= (nodeBurden ckd_a_ace_inhibitor) 0)
	(= (nodeBurden ckd_a_aspirin) 0)
	(= (nodeBurden ckd_a_lifestyle_management) 0)
	(= (nodeBurden ckd_d_egfr) 0)
	(= (nodeBurden ckd_d_hemoglobin_level) 0)
	(= (nodeBurden ckd_d_metabolic_abnormality) 0)
	(= (nodeBurden ckd_d_ferritin_level) 0)
	(= (nodeBurden ckd_p1) 0)
	(= (nodeBurden ckd_p2) 0)
	(= (nodeBurden ckd_p3) 0)
	(= (nodeBurden ckd_p4) 0)
	(= (nodeBurden ckd_p5) 0)
	(= (nodeBurden ckd_p6) 0)
	(= (nodeBurden ckd_d1) 0)
	(= (nodeBurden ckd_d2) 0)
	(= (nodeBurden ckd_d3) 0)
	(= (nodeBurden ckd_d4) 0)
	(= (nodeBurden htn_g) 0)
	(= (nodeBurden htn_a_lifestyle_management) 0)
	(= (nodeBurden htn_a_step1_acei) 0)
	(= (nodeBurden htn_a_step1_ccb) 0)
	(= (nodeBurden htn_a_step2_acei) 0)
	(= (nodeBurden htn_a_step2_diuretics) 0)
	(= (nodeBurden htn_a_step3_acei) 0)
	(= (nodeBurden htn_a_step3_ccb) 0)
	(= (nodeBurden htn_a_step3_diuretric) 0)
	(= (nodeBurden htn_a_specialist_consult) 0)
	(= (nodeBurden htn_d_age_under_55) 0)
	(= (nodeBurden htn_d_bp_controlled_1) 0)
	(= (nodeBurden htn_d_bp_controlled_2) 0)
	(= (nodeBurden htn_d_bp_controlled_3) 0)
	(= (nodeBurden htn_p1) 0)
	(= (nodeBurden htn_p2) 0)
	(= (nodeBurden htn_p3) 0)
	(= (nodeBurden htn_p4) 0)
	(= (nodeBurden htn_p5) 0)
	(= (nodeBurden htn_p6) 0)
	(= (nodeBurden htn_d1) 0)
	(= (nodeBurden htn_d2) 0)
	(= (nodeBurden htn_d3) 0)
	(= (nodeBurden rev-dummy-1) 0)
	(= (nodeBurden alt-40a95234) 0)
	(= (nodeBurden rev-dummy-2) 0)
	(= (nodeBurden alt-39999914) 0)
	(= (nodeBurden rev-afib-scb-1) 0)
	(= (nodeBurden alt-37536fba) 0)
	(= (nodeBurden rev-afib-scb-2) 0)
	(= (nodeBurden alt-c9ca60ae) 0)
	(= (nodeBurden rev-ckd-warfarin) 0)
	(= (nodeBurden alt-ed39ae97) 0)
	(= (nodeBurden rev-ckd-doac) 0)
	(= (nodeBurden alt-b0ef3768) 0)

	(= (nodeNonAdherence afib_g) 0)
	(= (nodeNonAdherence afib_a_cardioversion) 0)
	(= (nodeNonAdherence afib_a_anticoagulation) 0)
	(= (nodeNonAdherence afib_a_rate_control_1) 0)
	(= (nodeNonAdherence afib_a_rate_control_maintenance_1) 0)
	(= (nodeNonAdherence afib_a_rate_control_maintenance_2) 0)
	(= (nodeNonAdherence afib_a_rhytm_control_maintenance_1) 0)
	(= (nodeNonAdherence afib_a_rhytm_control_maintenance_2) 0)
	(= (nodeNonAdherence afib_a_pill_in_a_pocket) 0)
	(= (nodeNonAdherence afib_d_special_circumstances) 0)
	(= (nodeNonAdherence afib_d_afib_type) 0)
	(= (nodeNonAdherence afib_d_symptom_recurrence) 0)
	(= (nodeNonAdherence afib_d_symptoms_improve) 0)
	(= (nodeNonAdherence afib_d_symptoms_resolve) 0)
	(= (nodeNonAdherence afib_d_afib_recurs) 0)
	(= (nodeNonAdherence afib_d_tachychardia) 0)
	(= (nodeNonAdherence afib_p1) 0)
	(= (nodeNonAdherence afib_p2) 0)
	(= (nodeNonAdherence afib_p3) 0)
	(= (nodeNonAdherence afib_p4) 0)
	(= (nodeNonAdherence afib_d1) 0)
	(= (nodeNonAdherence afib_d2) 0)
	(= (nodeNonAdherence afib_d3) 0)
	(= (nodeNonAdherence afib_d4) 0)
	(= (nodeNonAdherence ckd_g) 0)
	(= (nodeNonAdherence ckd_a_phosphate_binders) 0)
	(= (nodeNonAdherence ckd_a_esa) 0)
	(= (nodeNonAdherence ckd_a_iron_therapy) 0)
	(= (nodeNonAdherence ckd_a_ace_inhibitor) 0)
	(= (nodeNonAdherence ckd_a_aspirin) 0)
	(= (nodeNonAdherence ckd_a_lifestyle_management) 0)
	(= (nodeNonAdherence ckd_d_egfr) 0)
	(= (nodeNonAdherence ckd_d_hemoglobin_level) 0)
	(= (nodeNonAdherence ckd_d_metabolic_abnormality) 0)
	(= (nodeNonAdherence ckd_d_ferritin_level) 0)
	(= (nodeNonAdherence ckd_p1) 0)
	(= (nodeNonAdherence ckd_p2) 0)
	(= (nodeNonAdherence ckd_p3) 0)
	(= (nodeNonAdherence ckd_p4) 0)
	(= (nodeNonAdherence ckd_p5) 0)
	(= (nodeNonAdherence ckd_p6) 0)
	(= (nodeNonAdherence ckd_d1) 0)
	(= (nodeNonAdherence ckd_d2) 0)
	(= (nodeNonAdherence ckd_d3) 0)
	(= (nodeNonAdherence ckd_d4) 0)
	(= (nodeNonAdherence htn_g) 0)
	(= (nodeNonAdherence htn_a_lifestyle_management) 0)
	(= (nodeNonAdherence htn_a_step1_acei) 0)
	(= (nodeNonAdherence htn_a_step1_ccb) 0)
	(= (nodeNonAdherence htn_a_step2_acei) 0)
	(= (nodeNonAdherence htn_a_step2_diuretics) 0)
	(= (nodeNonAdherence htn_a_step3_acei) 0)
	(= (nodeNonAdherence htn_a_step3_ccb) 0)
	(= (nodeNonAdherence htn_a_step3_diuretric) 0)
	(= (nodeNonAdherence htn_a_specialist_consult) 0)
	(= (nodeNonAdherence htn_d_age_under_55) 0)
	(= (nodeNonAdherence htn_d_bp_controlled_1) 0)
	(= (nodeNonAdherence htn_d_bp_controlled_2) 0)
	(= (nodeNonAdherence htn_d_bp_controlled_3) 0)
	(= (nodeNonAdherence htn_p1) 0)
	(= (nodeNonAdherence htn_p2) 0)
	(= (nodeNonAdherence htn_p3) 0)
	(= (nodeNonAdherence htn_p4) 0)
	(= (nodeNonAdherence htn_p5) 0)
	(= (nodeNonAdherence htn_p6) 0)
	(= (nodeNonAdherence htn_d1) 0)
	(= (nodeNonAdherence htn_d2) 0)
	(= (nodeNonAdherence htn_d3) 0)
	(= (nodeNonAdherence rev-dummy-1) 0)
	(= (nodeNonAdherence alt-40a95234) 0)
	(= (nodeNonAdherence rev-dummy-2) 0)
	(= (nodeNonAdherence alt-39999914) 0)
	(= (nodeNonAdherence rev-afib-scb-1) 0)
	(= (nodeNonAdherence alt-37536fba) 0)
	(= (nodeNonAdherence rev-afib-scb-2) 0)
	(= (nodeNonAdherence alt-c9ca60ae) 0)
	(= (nodeNonAdherence rev-ckd-warfarin) 0)
	(= (nodeNonAdherence alt-ed39ae97) 0)
	(= (nodeNonAdherence rev-ckd-doac) 0)
	(= (nodeNonAdherence alt-b0ef3768) 0)

	(= (nodeStartTime afib_g) 0)
	(= (nodeStartTime afib_a_cardioversion) 0)
	(= (nodeStartTime afib_a_anticoagulation) 0)
	(= (nodeStartTime afib_a_rate_control_1) 0)
	(= (nodeStartTime afib_a_rate_control_maintenance_1) 0)
	(= (nodeStartTime afib_a_rate_control_maintenance_2) 0)
	(= (nodeStartTime afib_a_rhytm_control_maintenance_1) 0)
	(= (nodeStartTime afib_a_rhytm_control_maintenance_2) 0)
	(= (nodeStartTime afib_a_pill_in_a_pocket) 0)
	(= (nodeStartTime afib_d_special_circumstances) 0)
	(= (nodeStartTime afib_d_afib_type) 0)
	(= (nodeStartTime afib_d_symptom_recurrence) 0)
	(= (nodeStartTime afib_d_symptoms_improve) 0)
	(= (nodeStartTime afib_d_symptoms_resolve) 0)
	(= (nodeStartTime afib_d_afib_recurs) 0)
	(= (nodeStartTime afib_d_tachychardia) 0)
	(= (nodeStartTime afib_p1) 0)
	(= (nodeStartTime afib_p2) 0)
	(= (nodeStartTime afib_p3) 0)
	(= (nodeStartTime afib_p4) 0)
	(= (nodeStartTime afib_d1) 0)
	(= (nodeStartTime afib_d2) 0)
	(= (nodeStartTime afib_d3) 0)
	(= (nodeStartTime afib_d4) 0)
	(= (nodeStartTime ckd_g) 0)
	(= (nodeStartTime ckd_a_phosphate_binders) 0)
	(= (nodeStartTime ckd_a_esa) 0)
	(= (nodeStartTime ckd_a_iron_therapy) 0)
	(= (nodeStartTime ckd_a_ace_inhibitor) 0)
	(= (nodeStartTime ckd_a_aspirin) 0)
	(= (nodeStartTime ckd_a_lifestyle_management) 0)
	(= (nodeStartTime ckd_d_egfr) 0)
	(= (nodeStartTime ckd_d_hemoglobin_level) 0)
	(= (nodeStartTime ckd_d_metabolic_abnormality) 0)
	(= (nodeStartTime ckd_d_ferritin_level) 0)
	(= (nodeStartTime ckd_p1) 0)
	(= (nodeStartTime ckd_p2) 0)
	(= (nodeStartTime ckd_p3) 0)
	(= (nodeStartTime ckd_p4) 0)
	(= (nodeStartTime ckd_p5) 0)
	(= (nodeStartTime ckd_p6) 0)
	(= (nodeStartTime ckd_d1) 0)
	(= (nodeStartTime ckd_d2) 0)
	(= (nodeStartTime ckd_d3) 0)
	(= (nodeStartTime ckd_d4) 0)
	(= (nodeStartTime htn_g) 0)
	(= (nodeStartTime htn_a_lifestyle_management) 0)
	(= (nodeStartTime htn_a_step1_acei) 0)
	(= (nodeStartTime htn_a_step1_ccb) 0)
	(= (nodeStartTime htn_a_step2_acei) 0)
	(= (nodeStartTime htn_a_step2_diuretics) 0)
	(= (nodeStartTime htn_a_step3_acei) 0)
	(= (nodeStartTime htn_a_step3_ccb) 0)
	(= (nodeStartTime htn_a_step3_diuretric) 0)
	(= (nodeStartTime htn_a_specialist_consult) 0)
	(= (nodeStartTime htn_d_age_under_55) 0)
	(= (nodeStartTime htn_d_bp_controlled_1) 0)
	(= (nodeStartTime htn_d_bp_controlled_2) 0)
	(= (nodeStartTime htn_d_bp_controlled_3) 0)
	(= (nodeStartTime htn_p1) 0)
	(= (nodeStartTime htn_p2) 0)
	(= (nodeStartTime htn_p3) 0)
	(= (nodeStartTime htn_p4) 0)
	(= (nodeStartTime htn_p5) 0)
	(= (nodeStartTime htn_p6) 0)
	(= (nodeStartTime htn_d1) 0)
	(= (nodeStartTime htn_d2) 0)
	(= (nodeStartTime htn_d3) 0)
	(= (nodeStartTime rev-dummy-1) 0)
	(= (nodeStartTime alt-40a95234) 0)
	(= (nodeStartTime rev-dummy-2) 0)
	(= (nodeStartTime alt-39999914) 0)
	(= (nodeStartTime rev-afib-scb-1) 0)
	(= (nodeStartTime alt-37536fba) 0)
	(= (nodeStartTime rev-afib-scb-2) 0)
	(= (nodeStartTime alt-c9ca60ae) 0)
	(= (nodeStartTime rev-ckd-warfarin) 0)
	(= (nodeStartTime alt-ed39ae97) 0)
	(= (nodeStartTime rev-ckd-doac) 0)
	(= (nodeStartTime alt-b0ef3768) 0)

	(= (nodeEndTime afib_g) 0)
	(= (nodeEndTime afib_a_cardioversion) 0)
	(= (nodeEndTime afib_a_anticoagulation) 0)
	(= (nodeEndTime afib_a_rate_control_1) 0)
	(= (nodeEndTime afib_a_rate_control_maintenance_1) 0)
	(= (nodeEndTime afib_a_rate_control_maintenance_2) 0)
	(= (nodeEndTime afib_a_rhytm_control_maintenance_1) 0)
	(= (nodeEndTime afib_a_rhytm_control_maintenance_2) 0)
	(= (nodeEndTime afib_a_pill_in_a_pocket) 0)
	(= (nodeEndTime afib_d_special_circumstances) 0)
	(= (nodeEndTime afib_d_afib_type) 0)
	(= (nodeEndTime afib_d_symptom_recurrence) 0)
	(= (nodeEndTime afib_d_symptoms_improve) 0)
	(= (nodeEndTime afib_d_symptoms_resolve) 0)
	(= (nodeEndTime afib_d_afib_recurs) 0)
	(= (nodeEndTime afib_d_tachychardia) 0)
	(= (nodeEndTime afib_p1) 0)
	(= (nodeEndTime afib_p2) 0)
	(= (nodeEndTime afib_p3) 0)
	(= (nodeEndTime afib_p4) 0)
	(= (nodeEndTime afib_d1) 0)
	(= (nodeEndTime afib_d2) 0)
	(= (nodeEndTime afib_d3) 0)
	(= (nodeEndTime afib_d4) 0)
	(= (nodeEndTime ckd_g) 0)
	(= (nodeEndTime ckd_a_phosphate_binders) 0)
	(= (nodeEndTime ckd_a_esa) 0)
	(= (nodeEndTime ckd_a_iron_therapy) 0)
	(= (nodeEndTime ckd_a_ace_inhibitor) 0)
	(= (nodeEndTime ckd_a_aspirin) 0)
	(= (nodeEndTime ckd_a_lifestyle_management) 0)
	(= (nodeEndTime ckd_d_egfr) 0)
	(= (nodeEndTime ckd_d_hemoglobin_level) 0)
	(= (nodeEndTime ckd_d_metabolic_abnormality) 0)
	(= (nodeEndTime ckd_d_ferritin_level) 0)
	(= (nodeEndTime ckd_p1) 0)
	(= (nodeEndTime ckd_p2) 0)
	(= (nodeEndTime ckd_p3) 0)
	(= (nodeEndTime ckd_p4) 0)
	(= (nodeEndTime ckd_p5) 0)
	(= (nodeEndTime ckd_p6) 0)
	(= (nodeEndTime ckd_d1) 0)
	(= (nodeEndTime ckd_d2) 0)
	(= (nodeEndTime ckd_d3) 0)
	(= (nodeEndTime ckd_d4) 0)
	(= (nodeEndTime htn_g) 0)
	(= (nodeEndTime htn_a_lifestyle_management) 0)
	(= (nodeEndTime htn_a_step1_acei) 0)
	(= (nodeEndTime htn_a_step1_ccb) 0)
	(= (nodeEndTime htn_a_step2_acei) 0)
	(= (nodeEndTime htn_a_step2_diuretics) 0)
	(= (nodeEndTime htn_a_step3_acei) 0)
	(= (nodeEndTime htn_a_step3_ccb) 0)
	(= (nodeEndTime htn_a_step3_diuretric) 0)
	(= (nodeEndTime htn_a_specialist_consult) 0)
	(= (nodeEndTime htn_d_age_under_55) 0)
	(= (nodeEndTime htn_d_bp_controlled_1) 0)
	(= (nodeEndTime htn_d_bp_controlled_2) 0)
	(= (nodeEndTime htn_d_bp_controlled_3) 0)
	(= (nodeEndTime htn_p1) 0)
	(= (nodeEndTime htn_p2) 0)
	(= (nodeEndTime htn_p3) 0)
	(= (nodeEndTime htn_p4) 0)
	(= (nodeEndTime htn_p5) 0)
	(= (nodeEndTime htn_p6) 0)
	(= (nodeEndTime htn_d1) 0)
	(= (nodeEndTime htn_d2) 0)
	(= (nodeEndTime htn_d3) 0)
	(= (nodeEndTime rev-dummy-1) 0)
	(= (nodeEndTime alt-40a95234) 0)
	(= (nodeEndTime rev-dummy-2) 0)
	(= (nodeEndTime alt-39999914) 0)
	(= (nodeEndTime rev-afib-scb-1) 0)
	(= (nodeEndTime alt-37536fba) 0)
	(= (nodeEndTime rev-afib-scb-2) 0)
	(= (nodeEndTime alt-c9ca60ae) 0)
	(= (nodeEndTime rev-ckd-warfarin) 0)
	(= (nodeEndTime alt-ed39ae97) 0)
	(= (nodeEndTime rev-ckd-doac) 0)
	(= (nodeEndTime alt-b0ef3768) 0)

	(= (nodeDuration afib_g) 0)
	(= (nodeDuration afib_a_cardioversion) 0)
	(= (nodeDuration afib_a_anticoagulation) 0)
	(= (nodeDuration afib_a_rate_control_1) 0)
	(= (nodeDuration afib_a_rate_control_maintenance_1) 0)
	(= (nodeDuration afib_a_rate_control_maintenance_2) 0)
	(= (nodeDuration afib_a_rhytm_control_maintenance_1) 0)
	(= (nodeDuration afib_a_rhytm_control_maintenance_2) 0)
	(= (nodeDuration afib_a_pill_in_a_pocket) 0)
	(= (nodeDuration afib_d_special_circumstances) 0)
	(= (nodeDuration afib_d_afib_type) 0)
	(= (nodeDuration afib_d_symptom_recurrence) 0)
	(= (nodeDuration afib_d_symptoms_improve) 0)
	(= (nodeDuration afib_d_symptoms_resolve) 0)
	(= (nodeDuration afib_d_afib_recurs) 0)
	(= (nodeDuration afib_d_tachychardia) 0)
	(= (nodeDuration afib_p1) 0)
	(= (nodeDuration afib_p2) 0)
	(= (nodeDuration afib_p3) 0)
	(= (nodeDuration afib_p4) 0)
	(= (nodeDuration afib_d1) 0)
	(= (nodeDuration afib_d2) 0)
	(= (nodeDuration afib_d3) 0)
	(= (nodeDuration afib_d4) 0)
	(= (nodeDuration ckd_g) 0)
	(= (nodeDuration ckd_a_phosphate_binders) 0)
	(= (nodeDuration ckd_a_esa) 0)
	(= (nodeDuration ckd_a_iron_therapy) 0)
	(= (nodeDuration ckd_a_ace_inhibitor) 0)
	(= (nodeDuration ckd_a_aspirin) 0)
	(= (nodeDuration ckd_a_lifestyle_management) 0)
	(= (nodeDuration ckd_d_egfr) 0)
	(= (nodeDuration ckd_d_hemoglobin_level) 0)
	(= (nodeDuration ckd_d_metabolic_abnormality) 0)
	(= (nodeDuration ckd_d_ferritin_level) 0)
	(= (nodeDuration ckd_p1) 0)
	(= (nodeDuration ckd_p2) 0)
	(= (nodeDuration ckd_p3) 0)
	(= (nodeDuration ckd_p4) 0)
	(= (nodeDuration ckd_p5) 0)
	(= (nodeDuration ckd_p6) 0)
	(= (nodeDuration ckd_d1) 0)
	(= (nodeDuration ckd_d2) 0)
	(= (nodeDuration ckd_d3) 0)
	(= (nodeDuration ckd_d4) 0)
	(= (nodeDuration htn_g) 0)
	(= (nodeDuration htn_a_lifestyle_management) 0)
	(= (nodeDuration htn_a_step1_acei) 0)
	(= (nodeDuration htn_a_step1_ccb) 0)
	(= (nodeDuration htn_a_step2_acei) 0)
	(= (nodeDuration htn_a_step2_diuretics) 0)
	(= (nodeDuration htn_a_step3_acei) 0)
	(= (nodeDuration htn_a_step3_ccb) 0)
	(= (nodeDuration htn_a_step3_diuretric) 0)
	(= (nodeDuration htn_a_specialist_consult) 0)
	(= (nodeDuration htn_d_age_under_55) 0)
	(= (nodeDuration htn_d_bp_controlled_1) 0)
	(= (nodeDuration htn_d_bp_controlled_2) 0)
	(= (nodeDuration htn_d_bp_controlled_3) 0)
	(= (nodeDuration htn_p1) 0)
	(= (nodeDuration htn_p2) 0)
	(= (nodeDuration htn_p3) 0)
	(= (nodeDuration htn_p4) 0)
	(= (nodeDuration htn_p5) 0)
	(= (nodeDuration htn_p6) 0)
	(= (nodeDuration htn_d1) 0)
	(= (nodeDuration htn_d2) 0)
	(= (nodeDuration htn_d3) 0)
	(= (nodeDuration rev-dummy-1) 0)
	(= (nodeDuration alt-40a95234) 0)
	(= (nodeDuration rev-dummy-2) 0)
	(= (nodeDuration alt-39999914) 0)
	(= (nodeDuration rev-afib-scb-1) 0)
	(= (nodeDuration alt-37536fba) 0)
	(= (nodeDuration rev-afib-scb-2) 0)
	(= (nodeDuration alt-c9ca60ae) 0)
	(= (nodeDuration rev-ckd-warfarin) 0)
	(= (nodeDuration alt-ed39ae97) 0)
	(= (nodeDuration rev-ckd-doac) 0)
	(= (nodeDuration alt-b0ef3768) 0)


	(= (total-cost) 0)
	(= (total-execcost) 0)
	(= (total-burden) 0)
	(= (total-nonadherence) 0)
	(= (total-duration) 0)
)

(:goal (and
	(treatmentPlanReady afib_c afib_g)
	(treatmentPlanReady ckd_c ckd_g)
	(treatmentPlanReady htn_c htn_g)
)
)

(:metric minimize
	(+ (total-cost)
(total-execcost)
(total-burden)
(total-nonadherence)
(total-duration)
))
)
