(define (problem mitplan-problem)
	(:domain mitplan-domain)
(:objects start-ckd start-htn start-afib - disease
	ckd-egfr ckd-hemoglobin ckd-ferritin ckd-metabolic-abnormality htn-age htn-bp-controlled-1 htn-bp-controlled-2 htn-bp-controlled-3 afib-special-circumstances afib-type afib-symptoms-resolve afib-high-burden-recurrence afib-symptoms-improve afib-tachycardia afib-afib-recurs ckd-ace-inhibitor ckd-aspirin ckd-lifestyle-management ckd-esa ckd-iron ckd-phosphate-binders htn-lifestyle-management htn-ccb-1 htn-ace-inhibitor-1 htn-ace-inhibitor-2 htn-diuretic-1 htn-ace-inhibitor-3 htn-ccb-2 htn-diuretic-2 htn-specialist-consult afib-warfarin-or-doac afib-bb-ccb-digoxin afib-cardioversion afib-bb-ccb-digoxin-combination afib-pill-in-a-pocket afib-dronedarone-flecainide-amiodarone goal-ckd goal-htn goal-afib  replace-aspirin replace-pcb - node
	ro-replace-aspirin ro-remove-bb ro-replace-pcb - revId
	DATA_ckd-egfr DATA_ckd-hemoglobin DATA_ckd-ferritin DATA_ckd-metabolic-abnormality DATA_htn-age DATA_htn-bp-controlled-1 DATA_htn-bp-controlled-2 DATA_htn-bp-controlled-3 DATA_afib-special-circumstances DATA_afib-type DATA_afib-symptoms-resolve DATA_afib-high-burden-recurrence DATA_afib-symptoms-improve DATA_afib-tachycardia DATA_afib-afib-recurs - DataItem
)
(:init
	(= (decisionBranchMin start-ckd ckd-egfr ckd-hemoglobin) 1)
	(= (decisionBranchMax start-ckd ckd-egfr ckd-hemoglobin) 1)
	(= (decisionBranchMin start-ckd ckd-egfr ckd-ace-inhibitor) 0)
	(= (decisionBranchMax start-ckd ckd-egfr ckd-ace-inhibitor) 0)
	(= (decisionBranchMin start-ckd ckd-egfr ckd-aspirin) 0)
	(= (decisionBranchMax start-ckd ckd-egfr ckd-aspirin) 0)
	(= (decisionBranchMin start-ckd ckd-egfr ckd-lifestyle-management) 0)
	(= (decisionBranchMax start-ckd ckd-egfr ckd-lifestyle-management) 0)
	(= (decisionBranchMin start-ckd ckd-egfr replace-aspirin) 0)
	(= (decisionBranchMax start-ckd ckd-egfr replace-aspirin) 0)
	(= (decisionBranchMin start-ckd ckd-hemoglobin ckd-ferritin) 0)
	(= (decisionBranchMax start-ckd ckd-hemoglobin ckd-ferritin) 0)
	(= (decisionBranchMin start-ckd ckd-hemoglobin ckd-esa) 1)
	(= (decisionBranchMax start-ckd ckd-hemoglobin ckd-esa) 1)
	(= (decisionBranchMin start-ckd ckd-ferritin ckd-iron) 1)
	(= (decisionBranchMax start-ckd ckd-ferritin ckd-iron) 1)
	(= (decisionBranchMin start-ckd ckd-ferritin ckd-metabolic-abnormality) 0)
	(= (decisionBranchMax start-ckd ckd-ferritin ckd-metabolic-abnormality) 0)
	(= (decisionBranchMin start-ckd ckd-metabolic-abnormality ckd-phosphate-binders) 1)
	(= (decisionBranchMax start-ckd ckd-metabolic-abnormality ckd-phosphate-binders) 1)
	(= (decisionBranchMin start-ckd ckd-metabolic-abnormality ckd-ace-inhibitor) 0)
	(= (decisionBranchMax start-ckd ckd-metabolic-abnormality ckd-ace-inhibitor) 0)
	(= (decisionBranchMin start-ckd ckd-metabolic-abnormality ckd-aspirin) 0)
	(= (decisionBranchMax start-ckd ckd-metabolic-abnormality ckd-aspirin) 0)
	(= (decisionBranchMin start-ckd ckd-metabolic-abnormality ckd-lifestyle-management) 0)
	(= (decisionBranchMax start-ckd ckd-metabolic-abnormality ckd-lifestyle-management) 0)
	(= (decisionBranchMin start-ckd ckd-metabolic-abnormality replace-aspirin) 0)
	(= (decisionBranchMax start-ckd ckd-metabolic-abnormality replace-aspirin) 0)
	(= (decisionBranchMin start-htn htn-age htn-ccb-1) 0)
	(= (decisionBranchMax start-htn htn-age htn-ccb-1) 0)
	(= (decisionBranchMin start-htn htn-age htn-ace-inhibitor-1) 1)
	(= (decisionBranchMax start-htn htn-age htn-ace-inhibitor-1) 1)
	(= (decisionBranchMin start-htn htn-bp-controlled-1 goal-htn) 1)
	(= (decisionBranchMax start-htn htn-bp-controlled-1 goal-htn) 1)
	(= (decisionBranchMin start-htn htn-bp-controlled-1 htn-ace-inhibitor-2) 0)
	(= (decisionBranchMax start-htn htn-bp-controlled-1 htn-ace-inhibitor-2) 0)
	(= (decisionBranchMin start-htn htn-bp-controlled-1 htn-diuretic-1) 0)
	(= (decisionBranchMax start-htn htn-bp-controlled-1 htn-diuretic-1) 0)
	(= (decisionBranchMin start-htn htn-bp-controlled-2 goal-htn) 1)
	(= (decisionBranchMax start-htn htn-bp-controlled-2 goal-htn) 1)
	(= (decisionBranchMin start-htn htn-bp-controlled-2 htn-ace-inhibitor-3) 0)
	(= (decisionBranchMax start-htn htn-bp-controlled-2 htn-ace-inhibitor-3) 0)
	(= (decisionBranchMin start-htn htn-bp-controlled-2 htn-ccb-2) 0)
	(= (decisionBranchMax start-htn htn-bp-controlled-2 htn-ccb-2) 0)
	(= (decisionBranchMin start-htn htn-bp-controlled-2 htn-diuretic-2) 0)
	(= (decisionBranchMax start-htn htn-bp-controlled-2 htn-diuretic-2) 0)
	(= (decisionBranchMin start-htn htn-bp-controlled-2 htn-bp-controlled-3) 0)
	(= (decisionBranchMax start-htn htn-bp-controlled-2 htn-bp-controlled-3) 0)
	(= (decisionBranchMin start-htn htn-bp-controlled-3 goal-htn) 1)
	(= (decisionBranchMax start-htn htn-bp-controlled-3 goal-htn) 1)
	(= (decisionBranchMin start-htn htn-bp-controlled-3 htn-specialist-consult) 0)
	(= (decisionBranchMax start-htn htn-bp-controlled-3 htn-specialist-consult) 0)
	(= (decisionBranchMin start-afib afib-special-circumstances afib-bb-ccb-digoxin) 0)
	(= (decisionBranchMax start-afib afib-special-circumstances afib-bb-ccb-digoxin) 0)
	(= (decisionBranchMin start-afib afib-special-circumstances afib-type) 1)
	(= (decisionBranchMax start-afib afib-special-circumstances afib-type) 1)
	(= (decisionBranchMin start-afib afib-type afib-cardioversion) 1)
	(= (decisionBranchMax start-afib afib-type afib-cardioversion) 1)
	(= (decisionBranchMin start-afib afib-type afib-high-burden-recurrence) 0)
	(= (decisionBranchMax start-afib afib-type afib-high-burden-recurrence) 0)
	(= (decisionBranchMin start-afib afib-symptoms-resolve afib-type) 0)
	(= (decisionBranchMax start-afib afib-symptoms-resolve afib-type) 0)
	(= (decisionBranchMin start-afib afib-symptoms-resolve afib-bb-ccb-digoxin-combination) 1)
	(= (decisionBranchMax start-afib afib-symptoms-resolve afib-bb-ccb-digoxin-combination) 1)
	(= (decisionBranchMin start-afib afib-symptoms-resolve goal-afib) 1)
	(= (decisionBranchMax start-afib afib-symptoms-resolve goal-afib) 1)
	(= (decisionBranchMin start-afib afib-symptoms-resolve goal-afib) 1)
	(= (decisionBranchMax start-afib afib-symptoms-resolve goal-afib) 1)
	(= (decisionBranchMin start-afib afib-symptoms-resolve goal-afib) 1)
	(= (decisionBranchMax start-afib afib-symptoms-resolve goal-afib) 1)
	(= (decisionBranchMin start-afib afib-high-burden-recurrence afib-pill-in-a-pocket) 0)
	(= (decisionBranchMax start-afib afib-high-burden-recurrence afib-pill-in-a-pocket) 0)
	(= (decisionBranchMin start-afib afib-high-burden-recurrence afib-dronedarone-flecainide-amiodarone) 1)
	(= (decisionBranchMax start-afib afib-high-burden-recurrence afib-dronedarone-flecainide-amiodarone) 1)
	(= (decisionBranchMin start-afib afib-high-burden-recurrence replace-pcb) 1)
	(= (decisionBranchMax start-afib afib-high-burden-recurrence replace-pcb) 1)
	(= (decisionBranchMin start-afib afib-symptoms-improve afib-tachycardia) 1)
	(= (decisionBranchMax start-afib afib-symptoms-improve afib-tachycardia) 1)
	(= (decisionBranchMin start-afib afib-symptoms-improve afib-afib-recurs) 1)
	(= (decisionBranchMax start-afib afib-symptoms-improve afib-afib-recurs) 1)
	(= (decisionBranchMin start-afib afib-symptoms-improve afib-bb-ccb-digoxin-combination) 0)
	(= (decisionBranchMax start-afib afib-symptoms-improve afib-bb-ccb-digoxin-combination) 0)
	(= (decisionBranchMin start-afib afib-symptoms-improve goal-afib) 0)
	(= (decisionBranchMax start-afib afib-symptoms-improve goal-afib) 0)
	(= (decisionBranchMin start-afib afib-symptoms-improve goal-afib) 0)
	(= (decisionBranchMax start-afib afib-symptoms-improve goal-afib) 0)
	(= (decisionBranchMin start-afib afib-symptoms-improve goal-afib) 0)
	(= (decisionBranchMax start-afib afib-symptoms-improve goal-afib) 0)
	(= (decisionBranchMin start-afib afib-tachycardia goal-afib) 0)
	(= (decisionBranchMax start-afib afib-tachycardia goal-afib) 0)
	(= (decisionBranchMin start-afib afib-tachycardia goal-afib) 1)
	(= (decisionBranchMax start-afib afib-tachycardia goal-afib) 1)
	(= (decisionBranchMin start-afib afib-tachycardia goal-afib) 1)
	(= (decisionBranchMax start-afib afib-tachycardia goal-afib) 1)
	(= (decisionBranchMin start-afib afib-tachycardia goal-afib) 1)
	(= (decisionBranchMax start-afib afib-tachycardia goal-afib) 1)
	(= (decisionBranchMin start-afib afib-tachycardia afib-bb-ccb-digoxin-combination) 1)
	(= (decisionBranchMax start-afib afib-tachycardia afib-bb-ccb-digoxin-combination) 1)
	(= (decisionBranchMin start-afib afib-afib-recurs goal-afib) 0)
	(= (decisionBranchMax start-afib afib-afib-recurs goal-afib) 0)
	(= (decisionBranchMin start-afib afib-afib-recurs afib-dronedarone-flecainide-amiodarone) 1)
	(= (decisionBranchMax start-afib afib-afib-recurs afib-dronedarone-flecainide-amiodarone) 1)
	(= (decisionBranchMin start-afib afib-afib-recurs replace-pcb) 1)
	(= (decisionBranchMax start-afib afib-afib-recurs replace-pcb) 1)

	(dataItem ckd-egfr DATA_ckd-egfr)
	(dataItem ckd-hemoglobin DATA_ckd-hemoglobin)
	(dataItem ckd-ferritin DATA_ckd-ferritin)
	(dataItem ckd-metabolic-abnormality DATA_ckd-metabolic-abnormality)
	(dataItem htn-age DATA_htn-age)
	(dataItem htn-bp-controlled-1 DATA_htn-bp-controlled-1)
	(dataItem htn-bp-controlled-2 DATA_htn-bp-controlled-2)
	(dataItem htn-bp-controlled-3 DATA_htn-bp-controlled-3)
	(dataItem afib-special-circumstances DATA_afib-special-circumstances)
	(dataItem afib-type DATA_afib-type)
	(dataItem afib-symptoms-resolve DATA_afib-symptoms-resolve)
	(dataItem afib-high-burden-recurrence DATA_afib-high-burden-recurrence)
	(dataItem afib-symptoms-improve DATA_afib-symptoms-improve)
	(dataItem afib-tachycardia DATA_afib-tachycardia)
	(dataItem afib-afib-recurs DATA_afib-afib-recurs)

	(= (dataValue DATA_ckd-ferritin) 0)
	(= (dataValue DATA_ckd-metabolic-abnormality) 0)
	(= (dataValue DATA_afib-symptoms-resolve) 1)
	(= (dataValue DATA_htn-age) 0)
	(= (dataValue DATA_htn-bp-controlled-3) 1)
	(= (dataValue DATA_ckd-hemoglobin) 1)
	(= (dataValue DATA_afib-high-burden-recurrence) 1)
	(= (dataValue DATA_afib-symptoms-improve) 1)
	(= (dataValue DATA_ckd-egfr) 1)
	(= (dataValue DATA_afib-special-circumstances) 1)
	(= (dataValue DATA_afib-tachycardia) 0)
	(= (dataValue DATA_afib-afib-recurs) 0)
	(= (dataValue DATA_afib-type) 0)
	(= (dataValue DATA_htn-bp-controlled-2) 1)
	(= (dataValue DATA_htn-bp-controlled-1) 0)

	(initialNode start-ckd ckd-egfr)
	(initialNode start-htn htn-age)
	(initialNode start-afib afib-warfarin-or-doac)
	(goalNode start-ckd goal-ckd)
	(goalNode start-htn goal-htn)
	(goalNode start-afib goal-afib)

	(predecessorNode ckd-egfr ckd-hemoglobin)
	(predecessorNode ckd-egfr ckd-ace-inhibitor)
	(predecessorNode ckd-egfr ckd-aspirin)
	(predecessorNode ckd-egfr ckd-lifestyle-management)
	(predecessorNode ckd-egfr replace-aspirin)
	(predecessorNode ckd-hemoglobin ckd-ferritin)
	(predecessorNode ckd-hemoglobin ckd-esa)
	(predecessorNode ckd-ace-inhibitor goal-ckd)
	(predecessorNode ckd-aspirin goal-ckd)
	(predecessorNode ckd-lifestyle-management goal-ckd)
	(predecessorNode ckd-ferritin ckd-iron)
	(predecessorNode ckd-ferritin ckd-metabolic-abnormality)
	(predecessorNode ckd-esa ckd-ferritin)
	(predecessorNode ckd-iron ckd-metabolic-abnormality)
	(predecessorNode ckd-metabolic-abnormality ckd-phosphate-binders)
	(predecessorNode ckd-metabolic-abnormality ckd-ace-inhibitor)
	(predecessorNode ckd-metabolic-abnormality ckd-aspirin)
	(predecessorNode ckd-metabolic-abnormality ckd-lifestyle-management)
	(predecessorNode ckd-metabolic-abnormality replace-aspirin)
	(predecessorNode ckd-phosphate-binders ckd-ace-inhibitor)
	(predecessorNode ckd-phosphate-binders ckd-aspirin)
	(predecessorNode ckd-phosphate-binders ckd-lifestyle-management)
	(predecessorNode ckd-phosphate-binders replace-aspirin)
	(predecessorNode htn-age htn-ccb-1)
	(predecessorNode htn-age htn-ace-inhibitor-1)
	(predecessorNode htn-lifestyle-management goal-htn)
	(predecessorNode htn-ccb-1 htn-bp-controlled-1)
	(predecessorNode htn-ace-inhibitor-1 htn-bp-controlled-1)
	(predecessorNode htn-bp-controlled-1 goal-htn)
	(predecessorNode htn-bp-controlled-1 htn-ace-inhibitor-2)
	(predecessorNode htn-bp-controlled-1 htn-diuretic-1)
	(predecessorNode htn-ace-inhibitor-2 htn-bp-controlled-2)
	(predecessorNode htn-diuretic-1 htn-bp-controlled-2)
	(predecessorNode htn-bp-controlled-2 goal-htn)
	(predecessorNode htn-bp-controlled-2 htn-ace-inhibitor-3)
	(predecessorNode htn-bp-controlled-2 htn-ccb-2)
	(predecessorNode htn-bp-controlled-2 htn-diuretic-2)
	(predecessorNode htn-bp-controlled-2 htn-bp-controlled-3)
	(predecessorNode htn-ace-inhibitor-3 goal-htn)
	(predecessorNode htn-ccb-2 goal-htn)
	(predecessorNode htn-diuretic-2 goal-htn)
	(predecessorNode htn-bp-controlled-3 goal-htn)
	(predecessorNode htn-bp-controlled-3 htn-specialist-consult)
	(predecessorNode htn-specialist-consult goal-htn)
	(predecessorNode afib-warfarin-or-doac goal-afib)
	(predecessorNode afib-special-circumstances afib-bb-ccb-digoxin)
	(predecessorNode afib-special-circumstances afib-type)
	(predecessorNode afib-bb-ccb-digoxin afib-symptoms-resolve)
	(predecessorNode afib-type afib-cardioversion)
	(predecessorNode afib-type afib-high-burden-recurrence)
	(predecessorNode afib-symptoms-resolve afib-type)
	(predecessorNode afib-symptoms-resolve afib-bb-ccb-digoxin-combination)
	(predecessorNode afib-symptoms-resolve goal-afib)
	(predecessorNode afib-cardioversion afib-symptoms-improve)
	(predecessorNode afib-high-burden-recurrence afib-pill-in-a-pocket)
	(predecessorNode afib-high-burden-recurrence afib-dronedarone-flecainide-amiodarone)
	(predecessorNode afib-high-burden-recurrence replace-pcb)
	(predecessorNode afib-bb-ccb-digoxin-combination goal-afib)
	(predecessorNode afib-symptoms-improve afib-tachycardia)
	(predecessorNode afib-symptoms-improve afib-afib-recurs)
	(predecessorNode afib-symptoms-improve afib-bb-ccb-digoxin-combination)
	(predecessorNode afib-symptoms-improve goal-afib)
	(predecessorNode afib-pill-in-a-pocket goal-afib)
	(predecessorNode afib-dronedarone-flecainide-amiodarone goal-afib)
	(predecessorNode afib-tachycardia goal-afib)
	(predecessorNode afib-tachycardia afib-bb-ccb-digoxin-combination)
	(predecessorNode afib-afib-recurs goal-afib)
	(predecessorNode afib-afib-recurs afib-dronedarone-flecainide-amiodarone)
	(predecessorNode afib-afib-recurs replace-pcb)
	(predecessorNode replace-aspirin goal-ckd)
	(predecessorNode replace-pcb goal-afib)

	(actionNode ckd-ace-inhibitor)
	(actionNode ckd-aspirin)
	(actionNode ckd-lifestyle-management)
	(actionNode ckd-esa)
	(actionNode ckd-iron)
	(actionNode ckd-phosphate-binders)
	(actionNode htn-lifestyle-management)
	(actionNode htn-ccb-1)
	(actionNode htn-ace-inhibitor-1)
	(actionNode htn-ace-inhibitor-2)
	(actionNode htn-diuretic-1)
	(actionNode htn-ace-inhibitor-3)
	(actionNode htn-ccb-2)
	(actionNode htn-diuretic-2)
	(actionNode htn-specialist-consult)
	(actionNode afib-warfarin-or-doac)
	(actionNode afib-bb-ccb-digoxin)
	(actionNode afib-cardioversion)
	(actionNode afib-bb-ccb-digoxin-combination)
	(actionNode afib-pill-in-a-pocket)
	(actionNode afib-dronedarone-flecainide-amiodarone)
	(decisionNode ckd-egfr)
	(decisionNode ckd-hemoglobin)
	(decisionNode ckd-ferritin)
	(decisionNode ckd-metabolic-abnormality)
	(decisionNode htn-age)
	(decisionNode htn-bp-controlled-1)
	(decisionNode htn-bp-controlled-2)
	(decisionNode htn-bp-controlled-3)
	(decisionNode afib-special-circumstances)
	(decisionNode afib-type)
	(decisionNode afib-symptoms-resolve)
	(decisionNode afib-high-burden-recurrence)
	(decisionNode afib-symptoms-improve)
	(decisionNode afib-tachycardia)
	(decisionNode afib-afib-recurs)
	(actionNode replace-aspirin)
	(actionNode replace-pcb)

	(originalAction ckd-ace-inhibitor)
	(originalAction ckd-aspirin)
	(originalAction ckd-lifestyle-management)
	(originalAction ckd-esa)
	(originalAction ckd-iron)
	(originalAction ckd-phosphate-binders)
	(originalAction htn-lifestyle-management)
	(originalAction htn-ccb-1)
	(originalAction htn-ace-inhibitor-1)
	(originalAction htn-ace-inhibitor-2)
	(originalAction htn-diuretic-1)
	(originalAction htn-ace-inhibitor-3)
	(originalAction htn-ccb-2)
	(originalAction htn-diuretic-2)
	(originalAction htn-specialist-consult)
	(originalAction afib-warfarin-or-doac)
	(originalAction afib-bb-ccb-digoxin)
	(originalAction afib-cardioversion)
	(originalAction afib-bb-ccb-digoxin-combination)
	(originalAction afib-pill-in-a-pocket)
	(originalAction afib-dronedarone-flecainide-amiodarone)

	(revisionAction replace-aspirin ro-replace-aspirin)
	(revisionAction replace-pcb ro-replace-pcb)

	(= (revisionFlag ckd-egfr ro-replace-aspirin) 0)
	(= (revisionFlag ckd-hemoglobin ro-replace-aspirin) 0)
	(= (revisionFlag ckd-ace-inhibitor ro-replace-aspirin) 0)
	(= (revisionFlag ckd-aspirin ro-replace-aspirin) 0)
	(= (revisionFlag ckd-lifestyle-management ro-replace-aspirin) 0)
	(= (revisionFlag ckd-ferritin ro-replace-aspirin) 0)
	(= (revisionFlag ckd-esa ro-replace-aspirin) 0)
	(= (revisionFlag ckd-iron ro-replace-aspirin) 0)
	(= (revisionFlag ckd-metabolic-abnormality ro-replace-aspirin) 0)
	(= (revisionFlag ckd-phosphate-binders ro-replace-aspirin) 0)
	(= (revisionFlag goal-ckd ro-replace-aspirin) 0)
	(= (revisionFlag htn-age ro-replace-aspirin) 0)
	(= (revisionFlag htn-lifestyle-management ro-replace-aspirin) 0)
	(= (revisionFlag htn-ccb-1 ro-replace-aspirin) 0)
	(= (revisionFlag htn-ace-inhibitor-1 ro-replace-aspirin) 0)
	(= (revisionFlag goal-htn ro-replace-aspirin) 0)
	(= (revisionFlag htn-bp-controlled-1 ro-replace-aspirin) 0)
	(= (revisionFlag htn-ace-inhibitor-2 ro-replace-aspirin) 0)
	(= (revisionFlag htn-diuretic-1 ro-replace-aspirin) 0)
	(= (revisionFlag htn-bp-controlled-2 ro-replace-aspirin) 0)
	(= (revisionFlag htn-ace-inhibitor-3 ro-replace-aspirin) 0)
	(= (revisionFlag htn-ccb-2 ro-replace-aspirin) 0)
	(= (revisionFlag htn-diuretic-2 ro-replace-aspirin) 0)
	(= (revisionFlag htn-bp-controlled-3 ro-replace-aspirin) 0)
	(= (revisionFlag htn-specialist-consult ro-replace-aspirin) 0)
	(= (revisionFlag afib-warfarin-or-doac ro-replace-aspirin) 0)
	(= (revisionFlag afib-special-circumstances ro-replace-aspirin) 0)
	(= (revisionFlag goal-afib ro-replace-aspirin) 0)
	(= (revisionFlag afib-bb-ccb-digoxin ro-replace-aspirin) 0)
	(= (revisionFlag afib-type ro-replace-aspirin) 0)
	(= (revisionFlag afib-symptoms-resolve ro-replace-aspirin) 0)
	(= (revisionFlag afib-cardioversion ro-replace-aspirin) 0)
	(= (revisionFlag afib-high-burden-recurrence ro-replace-aspirin) 0)
	(= (revisionFlag afib-bb-ccb-digoxin-combination ro-replace-aspirin) 0)
	(= (revisionFlag afib-symptoms-improve ro-replace-aspirin) 0)
	(= (revisionFlag afib-pill-in-a-pocket ro-replace-aspirin) 0)
	(= (revisionFlag afib-dronedarone-flecainide-amiodarone ro-replace-aspirin) 0)
	(= (revisionFlag afib-tachycardia ro-replace-aspirin) 0)
	(= (revisionFlag afib-afib-recurs ro-replace-aspirin) 0)
	(= (revisionFlag replace-aspirin ro-replace-aspirin) 0)
	(= (revisionFlag replace-pcb ro-replace-aspirin) 0)

	(= (revisionSequenceNumNodes ro-replace-aspirin) 0)
	(= (numNodesToReplace ro-replace-aspirin) 1)
	(= (revisionCount ro-replace-aspirin) 0)
	(= (revisionIDPass start-ckd ro-replace-aspirin) 0)
	(= (revisionIDPass start-htn ro-replace-aspirin) 0)
	(= (revisionIDPass start-afib ro-replace-aspirin) 0)

	(= (revisionFlag ckd-egfr ro-remove-bb) 0)
	(= (revisionFlag ckd-hemoglobin ro-remove-bb) 0)
	(= (revisionFlag ckd-ace-inhibitor ro-remove-bb) 1)
	(= (revisionFlag ckd-aspirin ro-remove-bb) 0)
	(= (revisionFlag ckd-lifestyle-management ro-remove-bb) 0)
	(= (revisionFlag ckd-ferritin ro-remove-bb) 0)
	(= (revisionFlag ckd-esa ro-remove-bb) 0)
	(= (revisionFlag ckd-iron ro-remove-bb) 0)
	(= (revisionFlag ckd-metabolic-abnormality ro-remove-bb) 0)
	(= (revisionFlag ckd-phosphate-binders ro-remove-bb) 0)
	(= (revisionFlag goal-ckd ro-remove-bb) 0)
	(= (revisionFlag htn-age ro-remove-bb) 0)
	(= (revisionFlag htn-lifestyle-management ro-remove-bb) 0)
	(= (revisionFlag htn-ccb-1 ro-remove-bb) 0)
	(= (revisionFlag htn-ace-inhibitor-1 ro-remove-bb) 0)
	(= (revisionFlag goal-htn ro-remove-bb) 0)
	(= (revisionFlag htn-bp-controlled-1 ro-remove-bb) 0)
	(= (revisionFlag htn-ace-inhibitor-2 ro-remove-bb) 0)
	(= (revisionFlag htn-diuretic-1 ro-remove-bb) 0)
	(= (revisionFlag htn-bp-controlled-2 ro-remove-bb) 0)
	(= (revisionFlag htn-ace-inhibitor-3 ro-remove-bb) 0)
	(= (revisionFlag htn-ccb-2 ro-remove-bb) 0)
	(= (revisionFlag htn-diuretic-2 ro-remove-bb) 0)
	(= (revisionFlag htn-bp-controlled-3 ro-remove-bb) 0)
	(= (revisionFlag htn-specialist-consult ro-remove-bb) 0)
	(= (revisionFlag afib-warfarin-or-doac ro-remove-bb) 0)
	(= (revisionFlag afib-special-circumstances ro-remove-bb) 0)
	(= (revisionFlag goal-afib ro-remove-bb) 0)
	(= (revisionFlag afib-bb-ccb-digoxin ro-remove-bb) 0)
	(= (revisionFlag afib-type ro-remove-bb) 0)
	(= (revisionFlag afib-symptoms-resolve ro-remove-bb) 0)
	(= (revisionFlag afib-cardioversion ro-remove-bb) 0)
	(= (revisionFlag afib-high-burden-recurrence ro-remove-bb) 0)
	(= (revisionFlag afib-bb-ccb-digoxin-combination ro-remove-bb) 0)
	(= (revisionFlag afib-symptoms-improve ro-remove-bb) 0)
	(= (revisionFlag afib-pill-in-a-pocket ro-remove-bb) 0)
	(= (revisionFlag afib-dronedarone-flecainide-amiodarone ro-remove-bb) 0)
	(= (revisionFlag afib-tachycardia ro-remove-bb) 0)
	(= (revisionFlag afib-afib-recurs ro-remove-bb) 0)
	(= (revisionFlag replace-aspirin ro-remove-bb) 0)
	(= (revisionFlag replace-pcb ro-remove-bb) 0)

	(= (revisionSequenceNumNodes ro-remove-bb) 1)
	(= (numNodesToReplace ro-remove-bb) 1)
	(= (revisionCount ro-remove-bb) 0)
	(= (revisionIDPass start-ckd ro-remove-bb) 0)
	(= (revisionIDPass start-htn ro-remove-bb) 0)
	(= (revisionIDPass start-afib ro-remove-bb) 0)

	(= (revisionFlag ckd-egfr ro-replace-pcb) 0)
	(= (revisionFlag ckd-hemoglobin ro-replace-pcb) 0)
	(= (revisionFlag ckd-ace-inhibitor ro-replace-pcb) 0)
	(= (revisionFlag ckd-aspirin ro-replace-pcb) 0)
	(= (revisionFlag ckd-lifestyle-management ro-replace-pcb) 0)
	(= (revisionFlag ckd-ferritin ro-replace-pcb) 0)
	(= (revisionFlag ckd-esa ro-replace-pcb) 0)
	(= (revisionFlag ckd-iron ro-replace-pcb) 0)
	(= (revisionFlag ckd-metabolic-abnormality ro-replace-pcb) 0)
	(= (revisionFlag ckd-phosphate-binders ro-replace-pcb) 0)
	(= (revisionFlag goal-ckd ro-replace-pcb) 0)
	(= (revisionFlag htn-age ro-replace-pcb) 0)
	(= (revisionFlag htn-lifestyle-management ro-replace-pcb) 0)
	(= (revisionFlag htn-ccb-1 ro-replace-pcb) 0)
	(= (revisionFlag htn-ace-inhibitor-1 ro-replace-pcb) 0)
	(= (revisionFlag goal-htn ro-replace-pcb) 0)
	(= (revisionFlag htn-bp-controlled-1 ro-replace-pcb) 0)
	(= (revisionFlag htn-ace-inhibitor-2 ro-replace-pcb) 0)
	(= (revisionFlag htn-diuretic-1 ro-replace-pcb) 0)
	(= (revisionFlag htn-bp-controlled-2 ro-replace-pcb) 0)
	(= (revisionFlag htn-ace-inhibitor-3 ro-replace-pcb) 0)
	(= (revisionFlag htn-ccb-2 ro-replace-pcb) 0)
	(= (revisionFlag htn-diuretic-2 ro-replace-pcb) 0)
	(= (revisionFlag htn-bp-controlled-3 ro-replace-pcb) 0)
	(= (revisionFlag htn-specialist-consult ro-replace-pcb) 0)
	(= (revisionFlag afib-warfarin-or-doac ro-replace-pcb) 0)
	(= (revisionFlag afib-special-circumstances ro-replace-pcb) 0)
	(= (revisionFlag goal-afib ro-replace-pcb) 0)
	(= (revisionFlag afib-bb-ccb-digoxin ro-replace-pcb) 0)
	(= (revisionFlag afib-type ro-replace-pcb) 0)
	(= (revisionFlag afib-symptoms-resolve ro-replace-pcb) 0)
	(= (revisionFlag afib-cardioversion ro-replace-pcb) 0)
	(= (revisionFlag afib-high-burden-recurrence ro-replace-pcb) 0)
	(= (revisionFlag afib-bb-ccb-digoxin-combination ro-replace-pcb) 0)
	(= (revisionFlag afib-symptoms-improve ro-replace-pcb) 0)
	(= (revisionFlag afib-pill-in-a-pocket ro-replace-pcb) 0)
	(= (revisionFlag afib-dronedarone-flecainide-amiodarone ro-replace-pcb) 0)
	(= (revisionFlag afib-tachycardia ro-replace-pcb) 0)
	(= (revisionFlag afib-afib-recurs ro-replace-pcb) 0)
	(= (revisionFlag replace-aspirin ro-replace-pcb) 0)
	(= (revisionFlag replace-pcb ro-replace-pcb) 0)

	(= (revisionSequenceNumNodes ro-replace-pcb) 0)
	(= (numNodesToReplace ro-replace-pcb) 1)
	(= (revisionCount ro-replace-pcb) 0)
	(= (revisionIDPass start-ckd ro-replace-pcb) 0)
	(= (revisionIDPass start-htn ro-replace-pcb) 0)
	(= (revisionIDPass start-afib ro-replace-pcb) 0)


	(= (allRevisionsPass start-ckd) 0)
	(= (allRevisionsPass start-htn) 0)
	(= (allRevisionsPass start-afib) 0)
	(= (numRevisionIDs start-ckd) 2)
	(= (numRevisionIDs start-htn) 0)
	(= (numRevisionIDs start-afib) 1)

	(anyRevisionOps start-ckd)
	(anyRevisionOps start-htn)
	(anyRevisionOps start-afib)

	(= (tentativeGoalCount) 0)

	(= (numGoals) 3)

	(= (total-execcost) 0)
	(= (total-cost) 0)
	(= (total-burden) 0)
	(= (total-nonadherence) 0)
	(= (total-duration) 0)

	(= (nodeExecCost ckd-egfr) 0)
	(= (nodeCost ckd-egfr) 0)
	(= (nodeBurden ckd-egfr) 0)
	(= (nodeNonadherence ckd-egfr) 0)
	(= (nodeStartTime ckd-egfr) 0)
	(= (nodeEndTime ckd-egfr) 0)
	(= (nodeDuration ckd-egfr) 0)

	(= (nodeExecCost ckd-hemoglobin) 0)
	(= (nodeCost ckd-hemoglobin) 0)
	(= (nodeBurden ckd-hemoglobin) 0)
	(= (nodeNonadherence ckd-hemoglobin) 0)
	(= (nodeStartTime ckd-hemoglobin) 0)
	(= (nodeEndTime ckd-hemoglobin) 0)
	(= (nodeDuration ckd-hemoglobin) 0)

	(= (nodeExecCost ckd-ace-inhibitor) 0)
	(= (nodeCost ckd-ace-inhibitor) 0)
	(= (nodeBurden ckd-ace-inhibitor) 0)
	(= (nodeNonadherence ckd-ace-inhibitor) 0)
	(= (nodeStartTime ckd-ace-inhibitor) 0)
	(= (nodeEndTime ckd-ace-inhibitor) 0)
	(= (nodeDuration ckd-ace-inhibitor) 0)

	(= (nodeExecCost ckd-aspirin) 0)
	(= (nodeCost ckd-aspirin) 0)
	(= (nodeBurden ckd-aspirin) 0)
	(= (nodeNonadherence ckd-aspirin) 0)
	(= (nodeStartTime ckd-aspirin) 0)
	(= (nodeEndTime ckd-aspirin) 0)
	(= (nodeDuration ckd-aspirin) 0)

	(= (nodeExecCost ckd-lifestyle-management) 0)
	(= (nodeCost ckd-lifestyle-management) 0)
	(= (nodeBurden ckd-lifestyle-management) 0)
	(= (nodeNonadherence ckd-lifestyle-management) 0)
	(= (nodeStartTime ckd-lifestyle-management) 0)
	(= (nodeEndTime ckd-lifestyle-management) 0)
	(= (nodeDuration ckd-lifestyle-management) 0)

	(= (nodeExecCost ckd-ferritin) 0)
	(= (nodeCost ckd-ferritin) 0)
	(= (nodeBurden ckd-ferritin) 0)
	(= (nodeNonadherence ckd-ferritin) 0)
	(= (nodeStartTime ckd-ferritin) 0)
	(= (nodeEndTime ckd-ferritin) 0)
	(= (nodeDuration ckd-ferritin) 0)

	(= (nodeExecCost ckd-esa) 0)
	(= (nodeCost ckd-esa) 0)
	(= (nodeBurden ckd-esa) 0)
	(= (nodeNonadherence ckd-esa) 0)
	(= (nodeStartTime ckd-esa) 0)
	(= (nodeEndTime ckd-esa) 0)
	(= (nodeDuration ckd-esa) 0)

	(= (nodeExecCost ckd-iron) 0)
	(= (nodeCost ckd-iron) 0)
	(= (nodeBurden ckd-iron) 0)
	(= (nodeNonadherence ckd-iron) 0)
	(= (nodeStartTime ckd-iron) 0)
	(= (nodeEndTime ckd-iron) 0)
	(= (nodeDuration ckd-iron) 0)

	(= (nodeExecCost ckd-metabolic-abnormality) 0)
	(= (nodeCost ckd-metabolic-abnormality) 0)
	(= (nodeBurden ckd-metabolic-abnormality) 0)
	(= (nodeNonadherence ckd-metabolic-abnormality) 0)
	(= (nodeStartTime ckd-metabolic-abnormality) 0)
	(= (nodeEndTime ckd-metabolic-abnormality) 0)
	(= (nodeDuration ckd-metabolic-abnormality) 0)

	(= (nodeExecCost ckd-phosphate-binders) 0)
	(= (nodeCost ckd-phosphate-binders) 0)
	(= (nodeBurden ckd-phosphate-binders) 0)
	(= (nodeNonadherence ckd-phosphate-binders) 0)
	(= (nodeStartTime ckd-phosphate-binders) 0)
	(= (nodeEndTime ckd-phosphate-binders) 0)
	(= (nodeDuration ckd-phosphate-binders) 0)

	(= (nodeExecCost goal-ckd) 0)
	(= (nodeCost goal-ckd) 0)
	(= (nodeBurden goal-ckd) 0)
	(= (nodeNonadherence goal-ckd) 0)
	(= (nodeStartTime goal-ckd) 0)
	(= (nodeEndTime goal-ckd) 0)
	(= (nodeDuration goal-ckd) 0)

	(= (nodeExecCost htn-age) 0)
	(= (nodeCost htn-age) 0)
	(= (nodeBurden htn-age) 0)
	(= (nodeNonadherence htn-age) 0)
	(= (nodeStartTime htn-age) 0)
	(= (nodeEndTime htn-age) 0)
	(= (nodeDuration htn-age) 0)

	(= (nodeExecCost htn-lifestyle-management) 0)
	(= (nodeCost htn-lifestyle-management) 0)
	(= (nodeBurden htn-lifestyle-management) 0)
	(= (nodeNonadherence htn-lifestyle-management) 0)
	(= (nodeStartTime htn-lifestyle-management) 0)
	(= (nodeEndTime htn-lifestyle-management) 0)
	(= (nodeDuration htn-lifestyle-management) 0)

	(= (nodeExecCost htn-ccb-1) 0)
	(= (nodeCost htn-ccb-1) 0)
	(= (nodeBurden htn-ccb-1) 0)
	(= (nodeNonadherence htn-ccb-1) 0)
	(= (nodeStartTime htn-ccb-1) 0)
	(= (nodeEndTime htn-ccb-1) 0)
	(= (nodeDuration htn-ccb-1) 0)

	(= (nodeExecCost htn-ace-inhibitor-1) 0)
	(= (nodeCost htn-ace-inhibitor-1) 0)
	(= (nodeBurden htn-ace-inhibitor-1) 0)
	(= (nodeNonadherence htn-ace-inhibitor-1) 0)
	(= (nodeStartTime htn-ace-inhibitor-1) 0)
	(= (nodeEndTime htn-ace-inhibitor-1) 0)
	(= (nodeDuration htn-ace-inhibitor-1) 0)

	(= (nodeExecCost goal-htn) 0)
	(= (nodeCost goal-htn) 0)
	(= (nodeBurden goal-htn) 0)
	(= (nodeNonadherence goal-htn) 0)
	(= (nodeStartTime goal-htn) 0)
	(= (nodeEndTime goal-htn) 0)
	(= (nodeDuration goal-htn) 0)

	(= (nodeExecCost htn-bp-controlled-1) 0)
	(= (nodeCost htn-bp-controlled-1) 0)
	(= (nodeBurden htn-bp-controlled-1) 0)
	(= (nodeNonadherence htn-bp-controlled-1) 0)
	(= (nodeStartTime htn-bp-controlled-1) 0)
	(= (nodeEndTime htn-bp-controlled-1) 0)
	(= (nodeDuration htn-bp-controlled-1) 0)

	(= (nodeExecCost htn-ace-inhibitor-2) 0)
	(= (nodeCost htn-ace-inhibitor-2) 0)
	(= (nodeBurden htn-ace-inhibitor-2) 0)
	(= (nodeNonadherence htn-ace-inhibitor-2) 0)
	(= (nodeStartTime htn-ace-inhibitor-2) 0)
	(= (nodeEndTime htn-ace-inhibitor-2) 0)
	(= (nodeDuration htn-ace-inhibitor-2) 0)

	(= (nodeExecCost htn-diuretic-1) 0)
	(= (nodeCost htn-diuretic-1) 0)
	(= (nodeBurden htn-diuretic-1) 0)
	(= (nodeNonadherence htn-diuretic-1) 0)
	(= (nodeStartTime htn-diuretic-1) 0)
	(= (nodeEndTime htn-diuretic-1) 0)
	(= (nodeDuration htn-diuretic-1) 0)

	(= (nodeExecCost htn-bp-controlled-2) 0)
	(= (nodeCost htn-bp-controlled-2) 0)
	(= (nodeBurden htn-bp-controlled-2) 0)
	(= (nodeNonadherence htn-bp-controlled-2) 0)
	(= (nodeStartTime htn-bp-controlled-2) 0)
	(= (nodeEndTime htn-bp-controlled-2) 0)
	(= (nodeDuration htn-bp-controlled-2) 0)

	(= (nodeExecCost htn-ace-inhibitor-3) 0)
	(= (nodeCost htn-ace-inhibitor-3) 0)
	(= (nodeBurden htn-ace-inhibitor-3) 0)
	(= (nodeNonadherence htn-ace-inhibitor-3) 0)
	(= (nodeStartTime htn-ace-inhibitor-3) 0)
	(= (nodeEndTime htn-ace-inhibitor-3) 0)
	(= (nodeDuration htn-ace-inhibitor-3) 0)

	(= (nodeExecCost htn-ccb-2) 0)
	(= (nodeCost htn-ccb-2) 0)
	(= (nodeBurden htn-ccb-2) 0)
	(= (nodeNonadherence htn-ccb-2) 0)
	(= (nodeStartTime htn-ccb-2) 0)
	(= (nodeEndTime htn-ccb-2) 0)
	(= (nodeDuration htn-ccb-2) 0)

	(= (nodeExecCost htn-diuretic-2) 0)
	(= (nodeCost htn-diuretic-2) 0)
	(= (nodeBurden htn-diuretic-2) 0)
	(= (nodeNonadherence htn-diuretic-2) 0)
	(= (nodeStartTime htn-diuretic-2) 0)
	(= (nodeEndTime htn-diuretic-2) 0)
	(= (nodeDuration htn-diuretic-2) 0)

	(= (nodeExecCost htn-bp-controlled-3) 0)
	(= (nodeCost htn-bp-controlled-3) 0)
	(= (nodeBurden htn-bp-controlled-3) 0)
	(= (nodeNonadherence htn-bp-controlled-3) 0)
	(= (nodeStartTime htn-bp-controlled-3) 0)
	(= (nodeEndTime htn-bp-controlled-3) 0)
	(= (nodeDuration htn-bp-controlled-3) 0)

	(= (nodeExecCost htn-specialist-consult) 0)
	(= (nodeCost htn-specialist-consult) 0)
	(= (nodeBurden htn-specialist-consult) 0)
	(= (nodeNonadherence htn-specialist-consult) 0)
	(= (nodeStartTime htn-specialist-consult) 0)
	(= (nodeEndTime htn-specialist-consult) 0)
	(= (nodeDuration htn-specialist-consult) 0)

	(= (nodeExecCost afib-warfarin-or-doac) 0)
	(= (nodeCost afib-warfarin-or-doac) 0)
	(= (nodeBurden afib-warfarin-or-doac) 0)
	(= (nodeNonadherence afib-warfarin-or-doac) 0)
	(= (nodeStartTime afib-warfarin-or-doac) 0)
	(= (nodeEndTime afib-warfarin-or-doac) 0)
	(= (nodeDuration afib-warfarin-or-doac) 0)

	(= (nodeExecCost afib-special-circumstances) 0)
	(= (nodeCost afib-special-circumstances) 0)
	(= (nodeBurden afib-special-circumstances) 0)
	(= (nodeNonadherence afib-special-circumstances) 0)
	(= (nodeStartTime afib-special-circumstances) 0)
	(= (nodeEndTime afib-special-circumstances) 0)
	(= (nodeDuration afib-special-circumstances) 0)

	(= (nodeExecCost goal-afib) 0)
	(= (nodeCost goal-afib) 0)
	(= (nodeBurden goal-afib) 0)
	(= (nodeNonadherence goal-afib) 0)
	(= (nodeStartTime goal-afib) 0)
	(= (nodeEndTime goal-afib) 0)
	(= (nodeDuration goal-afib) 0)

	(= (nodeExecCost afib-bb-ccb-digoxin) 0)
	(= (nodeCost afib-bb-ccb-digoxin) 0)
	(= (nodeBurden afib-bb-ccb-digoxin) 0)
	(= (nodeNonadherence afib-bb-ccb-digoxin) 0)
	(= (nodeStartTime afib-bb-ccb-digoxin) 0)
	(= (nodeEndTime afib-bb-ccb-digoxin) 0)
	(= (nodeDuration afib-bb-ccb-digoxin) 0)

	(= (nodeExecCost afib-type) 0)
	(= (nodeCost afib-type) 0)
	(= (nodeBurden afib-type) 0)
	(= (nodeNonadherence afib-type) 0)
	(= (nodeStartTime afib-type) 0)
	(= (nodeEndTime afib-type) 0)
	(= (nodeDuration afib-type) 0)

	(= (nodeExecCost afib-symptoms-resolve) 0)
	(= (nodeCost afib-symptoms-resolve) 0)
	(= (nodeBurden afib-symptoms-resolve) 0)
	(= (nodeNonadherence afib-symptoms-resolve) 0)
	(= (nodeStartTime afib-symptoms-resolve) 0)
	(= (nodeEndTime afib-symptoms-resolve) 0)
	(= (nodeDuration afib-symptoms-resolve) 0)

	(= (nodeExecCost afib-cardioversion) 0)
	(= (nodeCost afib-cardioversion) 0)
	(= (nodeBurden afib-cardioversion) 0)
	(= (nodeNonadherence afib-cardioversion) 0)
	(= (nodeStartTime afib-cardioversion) 0)
	(= (nodeEndTime afib-cardioversion) 0)
	(= (nodeDuration afib-cardioversion) 0)

	(= (nodeExecCost afib-high-burden-recurrence) 0)
	(= (nodeCost afib-high-burden-recurrence) 0)
	(= (nodeBurden afib-high-burden-recurrence) 0)
	(= (nodeNonadherence afib-high-burden-recurrence) 0)
	(= (nodeStartTime afib-high-burden-recurrence) 0)
	(= (nodeEndTime afib-high-burden-recurrence) 0)
	(= (nodeDuration afib-high-burden-recurrence) 0)

	(= (nodeExecCost afib-bb-ccb-digoxin-combination) 0)
	(= (nodeCost afib-bb-ccb-digoxin-combination) 0)
	(= (nodeBurden afib-bb-ccb-digoxin-combination) 0)
	(= (nodeNonadherence afib-bb-ccb-digoxin-combination) 0)
	(= (nodeStartTime afib-bb-ccb-digoxin-combination) 0)
	(= (nodeEndTime afib-bb-ccb-digoxin-combination) 0)
	(= (nodeDuration afib-bb-ccb-digoxin-combination) 0)

	(= (nodeExecCost afib-symptoms-improve) 0)
	(= (nodeCost afib-symptoms-improve) 0)
	(= (nodeBurden afib-symptoms-improve) 0)
	(= (nodeNonadherence afib-symptoms-improve) 0)
	(= (nodeStartTime afib-symptoms-improve) 0)
	(= (nodeEndTime afib-symptoms-improve) 0)
	(= (nodeDuration afib-symptoms-improve) 0)

	(= (nodeExecCost afib-pill-in-a-pocket) 0)
	(= (nodeCost afib-pill-in-a-pocket) 0)
	(= (nodeBurden afib-pill-in-a-pocket) 0)
	(= (nodeNonadherence afib-pill-in-a-pocket) 0)
	(= (nodeStartTime afib-pill-in-a-pocket) 0)
	(= (nodeEndTime afib-pill-in-a-pocket) 0)
	(= (nodeDuration afib-pill-in-a-pocket) 0)

	(= (nodeExecCost afib-dronedarone-flecainide-amiodarone) 0)
	(= (nodeCost afib-dronedarone-flecainide-amiodarone) 0)
	(= (nodeBurden afib-dronedarone-flecainide-amiodarone) 0)
	(= (nodeNonadherence afib-dronedarone-flecainide-amiodarone) 0)
	(= (nodeStartTime afib-dronedarone-flecainide-amiodarone) 0)
	(= (nodeEndTime afib-dronedarone-flecainide-amiodarone) 0)
	(= (nodeDuration afib-dronedarone-flecainide-amiodarone) 0)

	(= (nodeExecCost afib-tachycardia) 0)
	(= (nodeCost afib-tachycardia) 0)
	(= (nodeBurden afib-tachycardia) 0)
	(= (nodeNonadherence afib-tachycardia) 0)
	(= (nodeStartTime afib-tachycardia) 0)
	(= (nodeEndTime afib-tachycardia) 0)
	(= (nodeDuration afib-tachycardia) 0)

	(= (nodeExecCost afib-afib-recurs) 0)
	(= (nodeCost afib-afib-recurs) 0)
	(= (nodeBurden afib-afib-recurs) 0)
	(= (nodeNonadherence afib-afib-recurs) 0)
	(= (nodeStartTime afib-afib-recurs) 0)
	(= (nodeEndTime afib-afib-recurs) 0)
	(= (nodeDuration afib-afib-recurs) 0)

	(= (nodeExecCost replace-aspirin) 0)
	(= (nodeCost replace-aspirin) 0)
	(= (nodeBurden replace-aspirin) 0)
	(= (nodeNonadherence replace-aspirin) 0)
	(= (nodeStartTime replace-aspirin) 0)
	(= (nodeEndTime replace-aspirin) 0)
	(= (nodeDuration replace-aspirin) 0)

	(= (nodeExecCost replace-pcb) 0)
	(= (nodeCost replace-pcb) 0)
	(= (nodeBurden replace-pcb) 0)
	(= (nodeNonadherence replace-pcb) 0)
	(= (nodeStartTime replace-pcb) 0)
	(= (nodeEndTime replace-pcb) 0)
	(= (nodeDuration replace-pcb) 0)

)

(:goal (and	(treatmentPlanReady start-ckd goal-ckd)
	(treatmentPlanReady start-htn goal-htn)
	(treatmentPlanReady start-afib goal-afib)
	)
)

(:metric minimize
	(+ (total-execcost)
(total-cost)
(total-burden)
(total-nonadherence)
(total-duration)
))
)